### ISSUE TITLE
unable to tag an image with 'atomic images tag'

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#1000]
Using `atomic-1.17.1-4.fc25.x86_64` on my F25 system.

```
$ sudo atomic images list
   REPOSITORY                          TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   registry.centos.org/centos/centos   latest   5d7f51b6d39a   2017-04-06 15:03   192.48 MB      docker    
   registry.fedoraproject.org/fedora   latest   917d6b21e974   2017-03-29 23:17   230.59 MB      docker    

$ sudo atomic images tag registry.centos.org/centos/centos:latest my.registry.local/centos:latest
500 Server Error: Internal Server Error ("b'{"message":"invalid reference format"}'")

$ sudo atomic --debug images tag registry.centos.org/centos/centos:latest my.registry.local/centos:latest
Namespace(_class=<class 'Atomic.tag.Tag'>, assumeyes=False, debug=True, func='tag_image', ignore=False, profile=False, src='registry.centos.org/centos/centos:latest', storage=None, target='my.registry.local/centos:latest')
500 Server Error: Internal Server Error ("b'{"message":"invalid reference format"}'")
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.24/images/registry.centos.org/centos/centos:latest/tag?force=0&repo=my.registry.local%2Fcentos%3Alatest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/atomic", line 203, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.5/site-packages/Atomic/tag.py", line 32, in tag_image
    backend.tag_image(self.args.src, self.args.target)
  File "/usr/lib/python3.5/site-packages/Atomic/backends/_docker.py", line 605, in tag_image
    return self.d.tag(src, dest)
  File "/usr/lib/python3.5/site-packages/Atomic/client.py", line 66, in newfunc
    result = attr(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/docker/api/image.py", line 245, in tag
    self._raise_for_status(res)
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"invalid reference format"}'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/atomic", line 213, in <module>
    sys.exit(1)
SystemExit: 1
```

**Comment by baude** [comment]
Closing on @miabbott 's behalf.  Reopen if not satisfied.
