### ISSUE TITLE
'atomic run' using image with different tags returns error

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#1006]
Using git master (3c0cbc69eafffc6f9e192ebdaf48c05517ef130f)

1. I've pulled `fedora:25` and `fedora:26` from the Fedora registry
1. Run the `date` command using `fedora:25`
1. Run the `date` command using `fedora:26`
1. Blows up

```
# ./atomic images list
   REPOSITORY                          TAG  IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   registry.fedoraproject.org/fedora   25   40e6be3d1688   2017-05-12 05:48   230.85 MB      docker    
   registry.fedoraproject.org/fedora   26   57ae3032ccae   2016-12-15 17:44   211.51 MB      docker    

# ./atomic run registry.fedoraproject.org/fedora:25 date
docker run -t -i --name fedora registry.fedoraproject.org/fedora:25 date
Wed May 17 18:34:12 UTC 2017

# ./atomic containers list --all
   CONTAINER ID IMAGE                COMMAND              CREATED          STATE      BACKEND    RUNTIME   
   d9f2626df2ad registry.fedoraproje date                 2017-05-17 18:34 exited     docker     docker    

# docker ps -a
CONTAINER ID        IMAGE                                  COMMAND             CREATED             STATUS                      PORTS               NAMES
d9f2626df2ad        registry.fedoraproject.org/fedora:25   "date"              18 seconds ago      Exited (0) 17 seconds ago                       fedora

# ./atomic run registry.fedoraproject.org/fedora:26 date                                                                                                                            
fedora
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container \"d9f2626df2adcc2139b65e729c72700134452cb677ee8817265120611c6ce337\" does not exist\n"

# ./atomic --debug run registry.fedoraproject.org/fedora:26 date                                                                                                                    
fedora
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container \"d9f2626df2adcc2139b65e729c72700134452cb677ee8817265120611c6ce337\" does not exist\n"

Traceback (most recent call last):
  File "./atomic", line 203, in <module>
    sys.exit(_func())
  File "/root/atomic/Atomic/run.py", line 87, in run
    return be.run(con_obj, atomic=self, args=self.args)
  File "/root/atomic/Atomic/backends/_docker.py", line 538, in run
    return self._start(iobject, args, atomic)
  File "/root/atomic/Atomic/backends/_docker.py", line 666, in _start
    container_command)
  File "/root/atomic/Atomic/util.py", line 197, in check_call
    return subprocess.check_call(cmd, env=env, stdin=stdin, stderr=stderr, stdout=stdout, close_fds=True)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker', 'exec', '-t', '-i', 'fedora', 'date']' returned non-zero exit status 126
[root@fedora25cloud-dev atomic]# ./atomic run registry.fedoraproject.org/fedora:26 echo 'hello'
fedora
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container \"d9f2626df2adcc2139b65e729c72700134452cb677ee8817265120611c6ce337\" does not exist\n"
```

**Comment by miabbott** [comment]
No more tracebacks in git master (77e8acd36a)
