### ISSUE TITLE
atomic on ARM machines

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/atomic#1028]
I was trying to run atomic scanners on ARM CentOS machine. However I could not install the scanner on node. 

```
[root@apm-mustang-ev3-06 ~]# atomic install  registry.centos.org/pipeline-images/pipeline-scanner
docker run -it --rm --privileged -v /etc/atomic.d:/host/etc/atomic.d/ registry.centos.org/pipeline-images/pipeline-scanner sh /install.sh
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x7191a0, 0x4420196d20)
	/usr/lib/golang/src/runtime/panic.go:500 +0x390
github.com/urfave/cli.HandleAction.func1(0x44201292c0)
	/builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x2a0
panic(0x7191a0, 0x4420196d20)
	/usr/lib/golang/src/runtime/panic.go:458 +0x4c0
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x4420128be0, 0x4420026030, 0x4420128ce0)
	/builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x150
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x44200c6280, 0x8ea960, 0x4420196d20)
	/builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x458
main.glob..func8(0x442009ca00, 0x0, 0x0)
	/builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/main_unix.go:26 +0x50
reflect.Value.call(0x703820, 0x798df8, 0x13, 0x762d29, 0x4, 0x4420129240, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/golang/src/reflect/value.go:434 +0xdac
reflect.Value.Call(0x703820, 0x798df8, 0x13, 0x4420129240, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/reflect/value.go:302 +0x88
github.com/urfave/cli.HandleAction(0x703820, 0x798df8, 0x442009ca00, 0x0, 0x0)
	/builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x1d4
github.com/urfave/cli.Command.Run(0x762ef5, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7745bd, 0x51, 0x0, ...)
	/builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xd0c
github.com/urfave/cli.(*App).Run(0x44200e6000, 0x4420078060, 0x2, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x830
main.main()
	/builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/runc-b8dbc3b8e8d868723aec2fd5082e6547ec66cf58/main.go:137 +0xc48

[root@apm-mustang-ev3-06 ~]# rpm -q atomic
atomic-1.14.1-5.el7.aarch64

[root@apm-mustang-ev3-06 ~]# rpm -q docker
docker-1.12.5-14.el7.centos.aarch64

[root@apm-mustang-ev3-06 ~]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (AltArch) 

[root@apm-mustang-ev3-06 ~]# uname -r -v -p
4.5.0-19.el7.aarch64 #1 SMP Thu Dec 15 19:25:46 CST 2016 aarch64
```

What can be done if one wants to (atomic) scan containers for ARM ?

**Comment by rhatdan** [comment]
I think you need an OpenScap scanner container built for Arm?

**Comment by navidshaikh** [comment]
> I think you need an OpenScap scanner container built for Arm?

That's correct. Built the atomic scanner container with `centos/aarch64`  as base image. Build, install, scan worked successfully! Thanks!
