### ISSUE TITLE
Exceptions thrown when installing etcd system container on Fedora Atomic Host Rawhide

### ISSUE THREAD

**Issue by mike-nguyen** [projectatomic/atomic#1048]
I am receiving the following error while installing the etcd system container on Fedora Atomic Host Rawhide.

`TypeError: expected str, bytes or os.PathLike object, not NoneType`

```
[cloud-user@fedora system]$ sudo atomic --debug install --system --name=etcd registry.fedoraproject.org/f25/etcd
Namespace(_class=<class 'Atomic.install.Install'>, args=[], assumeyes=False, debug=True, display=False, func='install', ignore=False, image='registry.fedoraproject.org/f25/etcd', name='etcd', opt1=None, opt2=None, opt3=None, profile=False, remote=None, setvalues=None, storage=None, system=True, system_package='auto', user=False)
Extracting to /var/lib/containers/atomic/etcd.0
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/bin/atomic", line 203, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/install.py", line 132, in install
    return be.install(self.image, self.name)
  File "/usr/lib/python3.6/site-packages/Atomic/backends/_ostree.py", line 127, in install
    return self.syscontainers.install(image, name)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 227, in install
    return_value = self._install(image, name)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 367, in _install
    self._checkout(repo, name, image, 0, False, values=values, remote=self.args.remote, system_package=self.args.system_package)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 471, in _checkout
    system_package=system_package)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 817, in _do_checkout
    shutil.copyfile(unitfileout, os.path.join(prefix, destination, "%s.service" % name))
  File "/usr/lib64/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/atomic", line 231, in <module>
    sys.exit(1)
SystemExit: 1
```

```
[root@fedora ~]# rpm-ostree status
State: idle
Deployments:
● custom:fedora/rawhide/x86_64/atomic-host
                   Version: Rawhide.20170712.n.0 (2017-07-12 10:55:12)
                    Commit: c5bbfb9588e551a726016b636c3467c13c10e78e47e5ce38a95ce4ecdccdd103

  fedora-atomic:fedora/26/x86_64/atomic-host
                   Version: 26.85 (2017-07-07 13:13:05)
                    Commit: 2e4fcaff52c18cf705a2ecfa47d2ca60958f7443177974f24cc9ce07494b3317
              GPGSignature: Valid signature by E641850B77DF435378D1D7E2812A6B4B64DAB85D
[root@fedora ~]# rpm -qa atomic
atomic-1.18.1-4.fc27.x86_64
```

**Comment by yuqi-zhang** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1461994

**Comment by miabbott** [comment]
So this is fixed with #1032?

Unfortunate that Rawhide has an older version than what is shipping in F26

**Comment by miabbott** [comment]
@baude Can you build `atomic` 1.18.1-5 for rawhide?

**Comment by baude** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=20500087

**Comment by baude** [comment]
closing ... re open if not happy
