### ISSUE TITLE
Test failures on Fedora 26

### ISSUE THREAD

**Issue by jlebon** [projectatomic/atomic#1057]
See https://github.com/projectatomic/atomic/pull/1056.

On Fedora 26 AH, we have the following failures (among others):

```
==== ./tests/integration/test_dbus_client.py ====
Test 'test_ContainersList' passed.
Test 'test_DeleteContainer' passed.
Running clean up: docker rmi docker.io/library/busybox:1.24
Test 'test_Containers_Trim' skipped.
Traceback (most recent call last):
  File "./tests/integration/test_dbus_client.py", line 305, in <module>
    _tb()
  File "./tests/integration/test_dbus_client.py", line 86, in test_Diff
    self.dbus_client.Diff('atomic-test-1', 'atomic-test-3', rpms=True)
  File "<decorator-gen-4>", line 2, in Diff
  File "/usr/lib/python3.6/site-packages/slip/dbus/polkit.py", line 121, in _enable_proxy
    return func(*p, **k)
  File "/var/tmp/checkout/atomic_dbus_client.py", line 39, in Diff
    return self.dbus_object.Diff(first, second, rpms, no_files, names_only, diff_keywords, metadata, dbus_interface="org.atomic", timeout = 2147400)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: ValueError: Unable to generate manifest for atomic-test-1. 
Reason: b''
```

```
==== ./tests/integration/test_diff.sh ====
+ set -euo pipefail
+ IFS='
	'
+ GOMTREE=/usr/bin/gomtree
+ trap teardown EXIT
+ '[' '!' -e /usr/bin/gomtree ']'
+ setup
+ IMAGE=atomic-test-1
++ /usr/bin/docker create atomic-test-1 /bin/true
+ id1=f32a3c0b4ee55d29c0c74922ecf38f37a865686dad5df0171386b2780130a448
++ /usr/bin/docker create atomic-test-1 rpm -e vim-minimal
+ id2=40352c600c27113c9c1100e76e09b009b13888f75e93594279e589fade41132a
+ /usr/bin/docker start 40352c600c27113c9c1100e76e09b009b13888f75e93594279e589fade41132a
40352c600c27113c9c1100e76e09b009b13888f75e93594279e589fade41132a
++ /bin/true
+ OUTPUT=
+ atomic --debug diff -r -v f32a3c0b4ee55d29c0c74922ecf38f37a865686dad5df0171386b2780130a448 40352c600c27113c9c1100e76e09b009b13888f75e93594279e589fade41132a
Unable to generate manifest for f32a3c0b4ee55d29c0c74922ecf38f37a865686dad5df0171386b2780130a448. 
Reason: b''
```

```
==== ./tests/integration/test_system_containers_image.sh ====
...
+ assert_not_reached 'Failed to match: ' '>  busybox' /var/tmp/checkout/.tmp.9kA352aqlZ/images.out
+ echo 'Failed to match: ' '>  busybox' /var/tmp/checkout/.tmp.9kA352aqlZ/images.out
Failed to match:  >  busybox /var/tmp/checkout/.tmp.9kA352aqlZ/images.out
+ exit 1
+ teardown
+ set +o pipefail
+ atomic --debug -y containers delete busybox
+ ostree --repo=/var/tmp/checkout/.tmp.9kA352aqlZ/repo refs --delete ociimage
```

```
==== ./tests/integration/test_system_containers_runtime.sh ====
...
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
  File "/usr/lib64/python3.6/socket.py", line 185, in __getstate__
    raise TypeError("Cannot serialize socket object")
TypeError: Cannot serialize socket object
```

Some of them also happen on the Fedora 26 Cloud.

**Comment by baude** [comment]
im working on this

**Comment by baude** [comment]
@jlebon care to rebase and try your PR again ?

**Comment by jlebon** [comment]
@baude Still seeing many of the same issues unfortunately. Maybe just add on to that PR to make it easier to iterate? (Or alternatively cherry-pick my commit and iterate in your own branch).

**Comment by jlebon** [comment]
This was fixed by https://github.com/projectatomic/atomic/pull/1076.
