### ISSUE TITLE
Error setting up a proxy

### ISSUE THREAD

**Issue by judavi** [projectatomic/atomic#1059]
Hello,
I'm trying to use atomic with a proxy, so I'm doing:

[trevor@sd]$ sudo vi /etc/atomic.conf 

default_scanner:
default_docker: docker
registry_confdir: /etc/containers/registries.d/
discover_sigstores: true
sigstore_metadata_image: sigstore

default_storage: docker

**http_proxy=http://localhost:3128/**
#https_proxy=http://localhost:3128/
#no_proxy=

And when I try to run any command I got this error:

[trevor@sd]$ atomic --version
Traceback (most recent call last):
  File "/usr/bin/atomic", line 34, in <module>
    from Atomic import containers
  File "/usr/lib/python2.7/site-packages/Atomic/containers.py", line 8, in <module>
    from Atomic.backendutils import BackendUtils
  File "/usr/lib/python2.7/site-packages/Atomic/backendutils.py", line 6, in <module>
    ATOMIC_CONFIG = get_atomic_config()
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 391, in get_atomic_config
    return yaml_load(conf_file)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not found expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "/etc/atomic.conf", line 24, column 1
could not found expected ':'
  in "/etc/atomic.conf", line 25, column 1

Atomic version:

[trevor@sd]$ atomic --version
1.17.1

**Comment by judavi** [comment]
The issue is fixed on: https://github.com/projectatomic/atomic/commit/ae782515a043c5638c04c0d576fe2c47a9eab32a

Is because is YAML so the format is http_proxy: http://localhost:3128/
