### ISSUE TITLE
Can't run atomic command on Centos 7

### ISSUE THREAD

**Issue by Evalle** [projectatomic/atomic#1122]
When I run atomic from cli on an instance with non-graphical Centos 7 I recieved:
```
[root@esh-atomic:~] atomic
Traceback (most recent call last):
  File "/bin/atomic", line 35, in <module>
    from Atomic import diff
  File "/usr/lib/python2.7/site-packages/Atomic/diff.py", line 6, in <module>
    from . import mount
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 36, in <module>
    from gi.repository import GLib  # pylint: disable=no-name-in-module
ImportError: No module named gi.repository
``` 
Manual installation of `pyobject3` solved my issue

I think that the package `pygobject3` should be added as the dependency for `atomic` on Centos 7

System info:
```
[root@atomic:~] atomic --version
1.17.1

[root@atomic:~] cat /etc/*release
CentOS Linux release 7.3.1611 (Core)
GDC Image 26.16 (7f43db7)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core)
CentOS Linux release 7.3.1611 (Core)
```

**Comment by ashcrow** [comment]
@jasonbrooks do you have a few to double check this one?

**Comment by jasonbrooks** [comment]
I just tried this w/ atomic 1.20.1 on a regular (non-atomic) CentOS install, and didn't hit the error. I'll close it, we can reopen if it recurs.
