### ISSUE TITLE
Atomic on Fedora 26 Atomic Host fail with "string indices must be integers"

### ISSUE THREAD

**Issue by mscherer** [projectatomic/atomic#1145]
As told on #1144 , I just installed Fedora 26 atomic, and after patching for showing a traceback, I see this:
```
# /tmp/atomic install  --system openshift/origin-ansible
Traceback (most recent call last):
  File "/tmp/atomic", line 203, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/install.py", line 132, in install
    return be.install(self.image, self.name)
  File "/usr/lib/python3.6/site-packages/Atomic/backends/_ostree.py", line 127, in install
    return self.syscontainers.install(image, name)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 224, in install
    return_value = self._run_once(image, name)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 283, in _run_once
    image_id = SystemContainers._get_image_id_from_manifest(image_manifest) or image_id
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 503, in _get_image_id_from_manifest
    image_id = image_manifest['Digest']
TypeError: string indices must be integers
```

My version of atomic is
```
# atomic  -v
1.18.1
```

And the ostree version:
```
# rpm-ostree  status 
State: idle
Deployments:
● fedora-atomic-26:fedora/26/x86_64/atomic-host
                   Version: 26.157 (2017-10-29 14:42:37)
                    Commit: c099633883cd8d06895e32a14c63f6672072430c151de882223e4abe20efa7ca
```

Without --system, it work fine.

**Comment by mscherer** [comment]
Seems to be a duplicate of https://github.com/projectatomic/atomic/pull/1055 , so it need a backport Fedora side.
