### ISSUE TITLE
unable to install system container; "ostree:" is not supported in this build

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#1158]
In the [Fedora Atomic Host Continuous](https://pagure.io/fedora-atomic-host-continuous) composes, we've been seeing the following error when trying to install a system container:

```
# atomic install --system --name=etcd registry.fedoraproject.org/f26/etcd 
FATA[0000] Invalid destination name ostree:registry.fedoraproject.org/f26/etcd@/var/lib/containers/atomic/.storage/ostree: The transport "ostree:" is not supported in this build 
```

Due to test configuration issues, we didn't spot this until now, but it is present in the oldest commit available in the FAHC compose from Dec 10:

```
# rpm-ostree status
State: idle
Deployments:
● ostree://custom:fahc/27/x86_64/buildmaster
                   Version: 27.92 (2017-12-10 13:55:55)
                    Commit: ff371176ccc4f3666eff5fdaae353e27bd3081127572d27a71ffd21bde10d855

# rpm -q ostree ostree-libs atomic
ostree-2017.14.14-102f30f6cc601aeafd92481ff788bdd35e3f052d.ae5724db656c5858156ef17fdccb4e4d278ba192.fc27.x86_64
ostree-libs-2017.14.14-102f30f6cc601aeafd92481ff788bdd35e3f052d.ae5724db656c5858156ef17fdccb4e4d278ba192.fc27.x86_64
atomic-1.20.1-6.fc27.x86_64
```

I'll try to reproduce in other environments, but wanted to note the error for now.

**Comment by miabbott** [comment]
debug output

```
# atomic --debug install --system --name=etcd registry.fedoraproject.org/f26/etcd 
Namespace(_class=<class 'Atomic.install.Install'>, args=[], assumeyes=False, debug=True, display=False, func='install', ignore=False, image='registry.fedoraproject.org/f26/etcd', name='etcd', opt1=None, opt2=None, opt3=None, profile=False, remote=None, runtime=None, setvalues=None, storage=None, system=True, system_package='auto', user=False)
FATA[0000] Invalid destination name ostree:registry.fedoraproject.org/f26/etcd@/var/lib/containers/atomic/.storage/ostree: The transport "ostree:" is not supported in this build 

Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/install.py", line 124, in install
    be.pull_image(self.args.image, remote_image_obj, debug=self.args.debug)
  File "/usr/lib/python3.6/site-packages/Atomic/backends/_ostree.py", line 113, in pull_image
    return self.syscontainers.pull_image(image, **kwargs)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 200, in pull_image
    self._pull_image_to_ostree(self._get_ostree_repo(), image or self.args.image, True, src_creds=src_creds)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 186, in _pull_image_to_ostree
    self._check_system_oci_image(repo, image, upgrade, src_creds=src_creds)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 2038, in _check_system_oci_image
    return self._check_system_oci_image_skopeo_copy(repo, img, src_creds=src_creds)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 2053, in _check_system_oci_image_skopeo_copy
    util.skopeo_copy("docker://" + img, destination, dest_ostree_tmp_dir=temp_dir, insecure=insecure, src_creds=src_creds)
  File "/usr/lib/python3.6/site-packages/Atomic/util.py", line 453, in skopeo_copy
    return check_call(cmd, env=os.environ)
  File "/usr/lib/python3.6/site-packages/Atomic/util.py", line 215, in check_call
    return subprocess.check_call(cmd, env=env, stdin=stdin, stderr=stderr, stdout=stdout, close_fds=True)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/skopeo', 'copy', '--dest-ostree-tmp-dir', '/var/lib/containers/atomic/.qyesfzo1', 'docker://registry.fedoraproject.org/f26/etcd', 'ostree:registry.fedoraproject.org/f26/etcd@/var/lib/containers/atomic/.storage/ostree']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 201, in <module>
    sys.exit(e.returncode)
SystemExit: 1
```

**Comment by miabbott** [comment]
Well, based on that output, it looks like this is a `skopeo` problem...

**Comment by rhatdan** [comment]
@runcom ptal

**Comment by miabbott** [comment]
I tried my hand at a `git-bisect` between projectatomic/skopeo@d8e506c6480423e03d1b217d042ee0124238d388 and projectatomic/skopeo@5a8f21263050a127f26e42dd411bf7efb5754667, but I wasn't able to reproduce the error.

I did that on a F27 Cloud host with `ostree-2017.15-1.fc27.x86_64` installed (and also tried with `ostree-2017.14-2.fc27.x86_64`), but no joy.

**Comment by cgwalters** [comment]
I bet it's related to https://src.fedoraproject.org/rpms/skopeo/c/b92cb64669ca811bf214c0eafcf039246c8f0b35?branch=master

**Comment by cgwalters** [comment]
Which also got backported to the f27 branch...

**Comment by cgwalters** [comment]
Ping @lsm5 - :arrow_up: can be reverted now right that modularity has/will change to an "inherit from base stuff" approach right?

**Comment by cgwalters** [comment]
https://src.fedoraproject.org/rpms/skopeo/c/e10b235e702f784795e2ba2f2fe73b22ea447877?branch=master

**Comment by cgwalters** [comment]
Confirmed fixed in

```
# rpm-ostree status
State: idle
Deployments:
* ostree://fahc:fahc/27/x86_64/buildmaster
                   Version: 27.221 (2018-01-17 15:42:17)
                    Commit: 8e38c6a5140122d52c88249412031516f52e3704cd72cbb7cfdbe88d2a1418b4
```
