### ISSUE TITLE
Question: do we need to care about the following error case? 

### ISSUE THREAD

**Issue by peterbaouoft** [projectatomic/atomic#1189]
It turns out that we fail for container case when there is a file(instead of directory) in var/lib/containers/atomic

The output is like the following:
```
**==== ./tests/integration/test_containers_list.sh ====
+ set -euo pipefail
+ IFS='
        '
++ grep -v -- --debug
+ ATOMIC='/usr/bin/coverage
run
--source=./Atomic/
--branch
--append
atomic'
++ /bin/true
+ OUTPUT=
+ sort
+ /usr/bin/coverage run --source=./Atomic/ --branch --append atomic containers list --all -q -f runtime=docker
[Errno 20] Not a directory: '/var/lib/containers/atomic/config.json/info'
```

More detailed is like the following:
```
ERROR: test_images (test_images.TestImages)                                                              
----------------------------------------------------------------------                                   
Traceback (most recent call last):                                                                       
  File "/root/atomic/tests/unit/test_images.py", line 125, in test_images                                
    return_value = images.display_all_image_info()                                                       
  File "Atomic/images.py", line 159, in display_all_image_info                                           
    _images = self._get_images()                    
  File "Atomic/images.py", line 219, in _get_images 
    self._mark_used(_images)                        
  File "Atomic/images.py", line 308, in _mark_used                                                       
    all_containers = [x.image for x in self.be_utils.get_containers()]                                   
  File "Atomic/backendutils.py", line 157, in get_containers                                             
    con_objs += be.get_containers()                                                                      
  File "Atomic/backends/_ostree.py", line 110, in get_containers                                         
    return [self._make_container(x) for x in self.syscontainers.get_containers()]                        
  File "Atomic/syscontainers.py", line 1518, in get_containers                                           
    return self._get_containers_at(checkouts, False, containers) + self._get_containers_at(preinstalled, True, containers)                                                                                         
  File "Atomic/syscontainers.py", line 1482, in _get_containers_at                                       
    with open(os.path.join(fullpath, "info"), "r") as info_file:                                         
IOError: [Errno 20] Not a directory: '/var/lib/containers/atomic/config.json/info
```

```
[root@localhost atomic]# pwd
/var/lib/containers/atomic
[root@localhost atomic]# ls
config.json

```

The error is produced when running against test_suite using most upstream code. 

Dunno we should care about it tho.

**Comment by giuseppe** [comment]
/var/lib/containers/atomic should never a file.  Are you seeing this error on the CI or locally?

**Comment by peterbaouoft** [comment]
ah, sorry, I meant for examples like the following:
If I have 
/var/lib/containers/atomic/config.json, then all the test locally will fail because config.json is not a directory. I see the error locally when I write a file to `/var/lib/containers/atomic/`

**Comment by giuseppe** [comment]
well, we could  skip the files there that are not directories, but only atomic is supposed to have ownership for that directory.

**Comment by peterbaouoft** [comment]
> but only atomic is supposed to have ownership for that directory.

Sounds good, this thing is a minor, and I think this should not matter that much too. This issue was just a question to confirm my thoughts :). I will close this issue if you think it is fine to do so.

**Comment by peterbaouoft** [comment]
alrighty, closing this issue :-)
