### ISSUE TITLE
atomic mount inside a privileged container

### ISSUE THREAD

**Issue by dharmit** [projectatomic/atomic#1209]
I'm trying to do `atomic mount` from inside a privileged container that's got access to `/var/run/docker.sock`. But `atomic mount` doesn't work.

```bash
$ sudo docker run --privileged -it --rm -v /var/run/docker.sock:/var/run/docker.sock registry.centos.org/centos/centos bash

[root@853399672d33 /]# history
    1  yum install -y atomic docker
    2  atomic images list
    3  docker images
    4  atomic mount -o rw centos/centos:latest /mnt

[root@853399672d33 /]# atomic mount -o rw centos/centos:latest /mnt
[Errno 2] No such file or directory
```
From the host:

```bash
$ docker info
Containers: 11
 Running: 8
 Paused: 0
 Stopped: 3
Images: 42
Server Version: 1.12.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 7.797 GiB
Name: dharmit
ID: INSV:GDBP:6UGX:TCVG:VP6Z:LQOG:LBRQ:A7ZH:P6ZS:MUJX:7PKZ:23YW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 provider=kvm
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Registries: docker.io (secure)
```

Is this expected behavior?

**Comment by dharmit** [comment]
Eventually, I'd like to do `atomic scan` from inside a container so that I can build and scan container images in OpenShift.

**Comment by rhatdan** [comment]
This might have something to do with crossing mount namespaces?
Do you have /var/lib/docker mounted into the container?  Atomic mount mounts directly from the store not through the docker daemon.

**Comment by dharmit** [comment]
No, I didn't have `/var/lib/docker` mounted. I did that but it didn't help:

```bash
[root@771d1c8d4fbc /]# atomic --debug mount -o rw centos/centos:latest /mnt
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 186, in mount
    d.mount(self.image, self.options)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 467, in mount
    driver_mount_fn(identifier, options)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 573, in _mount_overlay2
    return self._mount_overlay(identifier, options, "overlay2")
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 579, in _mount_overlay
    cid = self._identifier_as_cid(identifier)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 414, in _identifier_as_cid
    _image = Image(identifier)
  File "/usr/lib/python2.7/site-packages/Atomic/objects/image.py", line 54, in __init__
    self._instantiate()
  File "/usr/lib/python2.7/site-packages/Atomic/objects/image.py", line 81, in _instantiate
    self._setup_common()
  File "/usr/lib/python2.7/site-packages/Atomic/objects/image.py", line 87, in _setup_common
    self.registry, self.repo, self.image, self.tag, self.digest = Decompose(decompose_name).all
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 968, in __init__
    self._decompose(input_name)
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 987, in _decompose
    if not is_network_address(reg):
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 975, in is_network_address
    if _input in [x['hostname'] for x in get_registries()]:
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 92, in get_registries
    if registries_tool_path() is not None:
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 79, in registries_tool_path
    return subprocess.check_output(['which', '--skip-alias','registries'], stderr=DEVNULL)
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[root@771d1c8d4fbc /]# mount | grep '/var/lib/docker'
overlay on / type overlay (rw,relatime,seclabel,lowerdir=/var/lib/docker/overlay2/l/BWW3QBALM7APMJYFKYBSLTEZWM:/var/lib/docker/overlay2/l/SDECI4FHS73XVCG4ICX75OCTY2,upperdir=/var/lib/docker/overlay2/64c7c62402798936a2cae3053836aae0cbee5b9184201c1177c7dc4e0746f585/diff,workdir=/var/lib/docker/overlay2/64c7c62402798936a2cae3053836aae0cbee5b9184201c1177c7dc4e0746f585/work)
/dev/sda1 on /var/lib/docker type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/sda1 on /var/lib/docker/containers type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
```

**Comment by rhatdan** [comment]
It looks like atomic command is looking for /etc/containers/registries.conf, so maybe need to volume mount in /etc/containers.

**Comment by dharmit** [comment]
This got fixed by ensuring that `atomic-registries` package is installed in CentOS based system. Thanks for your help @rhatdan
