### ISSUE TITLE
atomic install --system on Fedora Atomic 27 with selinux disabled fails with selinux OSError exception.

### ISSUE THREAD

**Issue by dirkboye** [projectatomic/atomic#1211]
On a Fedora 27 Atomic Host (with selinux disabled) there's following problem when running following command:

```
atomic --debug install --system --system-package=no --name=xxx-system xxx
```

```
Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/install.py", line 134, in install
    return be.install(self.image, self.name)
  File "/usr/lib/python3.6/site-packages/Atomic/backends/_ostree.py", line 128, in install
    return self.syscontainers.install(image, name)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 577, in install
    return_value = self._install(image, name)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 705, in _install
    self._checkout_wrapper(repo, name, image, 0, SystemContainers.CHECKOUT_MODE_INSTALL, values=values, remote=self.args.remote, system_package=self.args.system_package)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 816, in _checkout_wrapper
    return self._checkout(repo, options)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 847, in _checkout
    raise e
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 832, in _checkout
    return self._do_checkout(repo, options)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1080, in _do_checkout
    rootfs = self._prepare_rootfs_dirs(remote_path, options["destination"], extract_only=options["extract_only"])
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 375, in _prepare_rootfs_dirs
    self._create_rootfs(rootfs)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 241, in _create_rootfs
    selinux.setfscreatecon_raw(None)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 198, in <module>
    sys.exit(1)
SystemExit: 1
```

I fixed this issue by enclosing 
```
   selinux.setfscreatecon_raw(None)
```
in line 294 of **_Atomic/syscontainers.py_**: https://github.com/projectatomic/atomic/blob/master/Atomic/syscontainers.py#L294

inside an
```
   if selinux.is_selinux_enabled():
```

Would that be the correct way? If yes I can create a Pull request for that.

**Comment by giuseppe** [comment]
closing the issue as the PR was merged
