### ISSUE TITLE
Add optX to stop subcommand

### ISSUE THREAD

**Issue by vpavlin** [projectatomic/atomic#169]
It seems `--optX` is missing from `atomic stop`

```
[vagrant@localhost ~ vagrant]
$ atomic install -h | egrep "opt1"
usage: atomic install [-h] [--opt1 OPT1] [--opt2 OPT2] [--opt3 OPT3] [-n NAME]
  --opt1 OPT1           additional arguments to be passed as ${OPT1} for
[vagrant@localhost ~ vagrant]
$ atomic uninstall -h | egrep "opt1"
usage: atomic uninstall [-h] [--opt1 OPT1] [--opt2 OPT2] [--opt3 OPT3]
  --opt1 OPT1           additional arguments to be passed as ${OPT1} for
[vagrant@localhost ~ vagrant]
$ atomic run -h | egrep "opt1"
usage: atomic run [-h] [--opt1 OPT1] [--opt2 OPT2] [--opt3 OPT3] [-n NAME]
  --opt1 OPT1           additional arguments to be passed as ${OPT1} for run
[vagrant@localhost ~ vagrant]
$ atomic stop -h | egrep "opt1"
[vagrant@localhost ~ vagrant]
```

Can it be added? I get 

```
$ atomic stop projectatomic/helloapache
Traceback (most recent call last):
  File "/usr/bin/atomic", line 248, in <module>
    sys.exit(args.func())
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 381, in stop
    self.display(cmd)
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 719, in display
    subprocess.check_call("/usr/bin/echo \"" + cmd  + "\"", env=self.cmd_env, shell=True)
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 453, in cmd_env
    if self.args.opt1:
AttributeError: 'Namespace' object has no attribute 'opt1'
```

**Comment by vpavlin** [comment]
Clone of #137

**Comment by vpavlin** [comment]
Sorry:/

**Comment by dustymabe** [comment]
I don't think this is a clone of #137 . #137 simply made errors go away because opt* wasn't supported for stop. I think was this issue is saying is that opt* should be supported for stop too?

**Comment by rhatdan** [comment]
Should we just remote opt* support and make users set it in environment?

I would make the options disappear but still work, I think.
