### ISSUE TITLE
atomic fails to build without dockerd running 

### ISSUE THREAD

**Issue by baude** [projectatomic/atomic#302]
It appears that the addition of docker.AutoversionClient requires that dockerd be running in order to work correctly.

```
>>> c = docker.Client()
>>> c = docker.AutoVersionClient()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 337, in __init__
    super(AutoVersionClient, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```
Because setup.py imports atomic content, unless dockerd is running, the build will fail like so:

```
[bbaude@localhost atomic (verify_name)]$ make
/usr/bin/python setup.py build
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import Atomic as _Atomic
  File "/home/bbaude/docker/atomic/Atomic/__init__.py", line 3, in <module>
    from .atomic import Atomic
  File "/home/bbaude/docker/atomic/Atomic/atomic.py", line 25, in <module>
    from .Export import export_docker
  File "/home/bbaude/docker/atomic/Atomic/Export.py", line 14, in <module>
    DOCKER_CLIENT = docker.AutoVersionClient(**kwargs_from_env())
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 337, in __init__
    super(AutoVersionClient, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
Makefile:20: recipe for target 'python-build' failed
make: *** [python-build] Error 1
```

One idea would be to do a try/except on the autoversion.

This was added in this PR -> https://github.com/projectatomic/atomic/commit/43bebd5647a528c2bf06d8686f1eb7ea4bfb7404

**Comment by baude** [comment]
I talked with @TomasTomecek  and I will dummy up a PR for everyone to review.

**Comment by rhatdan** [comment]
Yes I think we should try/except this.
