### ISSUE TITLE
hidden exception, no info when there are problems with docker api

### ISSUE THREAD

**Issue by optak** [projectatomic/atomic#312]
If atomic and docker has different version of docker api,
atomic.py fais like this:
```
Traceback (most recent call last):
  File "/bin/atomic", line 524, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/run.py", line 46, in run
    args = self._get_args("RUN")
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 361, in _get_args
    labels = self._get_labels()
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 279, in _get_labels
    return self._getconfig("Labels", [])
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 266, in _getconfig
    assert self.inspect is not None
```
The root cause is hidden because of strangly written functions  _inspect_image and _inspect_container:
```python
        except docker.errors.APIError:
            pass
```
I'm not sure if there is any good reason for this, but in my case, it made investigating issue much harder.
This is expeption hidden by ```pass```:
```400 Client Error: Bad Request ("client is newer than server (client API version: 1.21, server API version: 1.20)")```

Similar constructions can be found also on other places of atomic.py, couldn't be there at least some warning what is happening?

**Comment by rhatdan** [comment]
Yes I believe we should remove this pass.

**Comment by jwhonce** [comment]
@rhatdan In light of https://github.com/projectatomic/atomic/pull/321 should this issue be closed?
