### ISSUE TITLE
make test fail

### ISSUE THREAD

**Issue by tuxdna** [projectatomic/atomic#319]
Issues I observed with `make test`

- [ ] Need to do sudo ( on Fedora ) to run tests. Is this a good idea ? We should be able to run against a remote Docker server.
- [ ] `requirements.txt` is not used by `make test` to install dependencies

Create a virtualenv:

```
$ virtualenv env-atomic
$ source env-atomic/bin/env
```

Run tests:

```
(env-atomic)[saleem@example atomic]$ sudo make test
./test.sh
Pulling standard images from Docker Hub...
Building images from tests/test-images...
	Skipped : atomic-test-3
	Skipped : atomic-test-2
	Skipped : atomic-test-4
	Built   : atomic-test-secret
	Skipped : atomic-test-1
UNIT TESTS:
EE
======================================================================
ERROR: test_util (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_util
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/saleem/cdk/atomic/tests/unit/test_util.py", line 4, in <module>
    from Atomic import util
  File "Atomic/__init__.py", line 1, in <module>
    from .pulp import PulpServer, PulpConfig
  File "Atomic/pulp.py", line 11, in <module>
    from . import util
  File "Atomic/util.py", line 8, in <module>
    from .client import get_docker_client
  File "Atomic/client.py", line 1, in <module>
    import docker
ImportError: No module named docker


======================================================================
ERROR: test_mount (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_mount
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/saleem/cdk/atomic/tests/unit/test_mount.py", line 3, in <module>
    from Atomic import mount
  File "Atomic/__init__.py", line 1, in <module>
    from .pulp import PulpServer, PulpConfig
  File "Atomic/pulp.py", line 11, in <module>
    from . import util
  File "Atomic/util.py", line 8, in <module>
    from .client import get_docker_client
  File "Atomic/client.py", line 1, in <module>
    import docker
ImportError: No module named docker


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)

INTEGRATION TESTS:
Running test test_pass.sh...		PASS
Running test test_display.sh...		FAIL
Running test test_help.sh...		FAIL
Running test test_top.sh...		FAIL
Running test test_verify.sh...		PASS
Running test test_diff.sh...		FAIL
Running test test_mount.sh...		FAIL
Running test test_info.sh...		FAIL
Running test test_migrate.sh...		PASS
Coverage report:
Name                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------
Atomic/Export.py         57     57     24      0     0%
Atomic/Import.py         42     42     12      0     0%
Atomic/__init__.py        7      6      0      0    14%
Atomic/atomic.py        691    691    314      0     1%
Atomic/client.py          7      6      0      0    14%
Atomic/diff.py          207    207     80      0     0%
Atomic/help.py           59     59     10      0     0%
Atomic/mount.py         290    290     94      0     0%
Atomic/pulp.py          157    150     44      0     4%
Atomic/run.py            62     62     34      0     0%
Atomic/satellite.py     213    213     92      0     1%
Atomic/top.py           116    116     64      0     1%
Atomic/util.py          159    151     72      0     3%
Atomic/verify.py        176    176     81      0     0%
-------------------------------------------------------
TOTAL                  2243   2226    921      0     1%
Unit tests failed.
Integration test failures: 6
See /home/saleem/cdk/atomic/tests.log for more information.
Makefile:16: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by rhatdan** [comment]
You need to install python3-docker-py or python-docker-py

**Comment by rhatdan** [comment]
We can look at running atomic as non root, but currently running docker on a public ip or even opening the docker.sock to be usable by non privileged users, is incredibly unsafe, and not something we should encourage.  It basically opens up a full root acount to the user without any authentication or logging.

**Comment by tuxdna** [comment]
After following patch it works for me:

 * https://github.com/tuxdna/atomic/commit/6e38222a3079b4526340cf7af9e3ae820b53f5bf

```
$ sudo make test
[sudo] password for saleem: 
./test.sh
You are using pip version 7.1.0, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): requests>=2.4.3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Collecting docker-py (from -r requirements.txt (line 3))
  Downloading docker-py-1.7.2.tar.gz (68kB)
    100% |████████████████████████████████| 69kB 173kB/s 
Collecting websocket-client>=0.11.0 (from -r requirements.txt (line 4))
  Downloading websocket_client-0.35.0.tar.gz (193kB)
    100% |████████████████████████████████| 196kB 2.1MB/s 
Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): urllib3==1.13.1 in /usr/lib/python2.7/site-packages (from requests>=2.4.3->-r requirements.txt (line 1))
Installing collected packages: websocket-client, docker-py
  Running setup.py install for websocket-client
  Running setup.py install for docker-py
Successfully installed docker-py-1.7.2 websocket-client-0.35.0
UNIT TESTS:
Pulling standard images from Docker Hub...
Building images from tests/test-images...
	Skipped : atomic-test-3
	Skipped : atomic-test-2
	Skipped : atomic-test-4
	Built   : atomic-test-secret
	Skipped : atomic-test-1
...........
----------------------------------------------------------------------
Ran 11 tests in 1.629s

OK

INTEGRATION TESTS:
Running test test_pass.sh...		PASS
Running test test_display.sh...		PASS
Running test test_help.sh...		PASS
Running test test_top.sh...		PASS
Running test test_verify.sh...		PASS
Running test test_diff.sh...		PASS
Running test test_mount.sh...		PASS
Running test test_info.sh...		PASS
Running test test_migrate.sh...		PASS
Coverage report:
Name                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------
Atomic/Export.py         57     46     24      0    14%
Atomic/Import.py         42     32     12      0    19%
Atomic/__init__.py        7      0      0      0   100%
Atomic/atomic.py        691    433    314     22    31%
Atomic/client.py          7      2      0      0    71%
Atomic/diff.py          207     17     80     19    86%
Atomic/help.py           59      3     10      3    91%
Atomic/mount.py         290    100     94     22    63%
Atomic/pulp.py          157    130     44      0    14%
Atomic/run.py            62     26     34      9    51%
Atomic/satellite.py     213    186     92      0    10%
Atomic/top.py           116     18     64     14    74%
Atomic/util.py          159     89     72      8    41%
Atomic/verify.py        176    147     81      3    13%
-------------------------------------------------------
TOTAL                  2243   1229    921    100    40%
ALL TESTS PASSED

```

**Comment by tuxdna** [comment]
Below is the patch. The idea is to ensure we have all the requirements / and tools ready before we even start building docker images.

```diff
diff --git a/test.sh b/test.sh
index d947d15..185b9c9 100755
--- a/test.sh
+++ b/test.sh
@@ -111,7 +111,8 @@ make_docker_images () {
     done
 }
 
-make_docker_images
+# ensure dependencies are installed
+pip install -r requirements.txt
 
 # Python unit tests.
 echo "UNIT TESTS:"
@@ -129,6 +130,13 @@ if [[ ! -x "${COVERAGE_BIN}" ]]; then
   COVERAGE_BIN="/usr/bin/coverage2"
 fi
 
+if [[ ! -x "${COVERAGE_BIN}" ]]; then
+    echo "Cannot run tests without an executable $COVERAGE_BIN tool"
+    exit -1
+fi
+
+make_docker_images
+
 set +e
 COVERAGE="${COVERAGE_BIN}
 run
```

**Comment by tuxdna** [comment]
@rhatdan Regarding, non-root users. I think, given a user has Docker daemon has setup TLS / Certificates properly, s/he should be able to provide that information from CLI  / env variables, when running make test.

Something like:

```
$ export DOCKER_HOST=tcp://172.13.14.1:5555
$ export DOCKER_CERT_PATH=/home/foo/bar/adb/.vagrant/machines/default/virtualbox/.docker
$ export DOCKER_TLS_VERIFY=1
$ export DOCKER_MACHINE_NAME="90d3e96"
make test
```

**Comment by tuxdna** [comment]
I managed to setup docker with TLS, so now I can run docker without sudo. Here are the steps:

https://gist.github.com/tuxdna/0fd962480bc8560ce509

**Comment by rhatdan** [comment]
That is fine, but doesn't that allow every process on one host to become root on the other machine with no logging

**Comment by tuxdna** [comment]
@rhatdan Perhaps, I didn't understand your concern. 

Do you mean that one can somehow also become root on the docker host, using TLS mechanism ?

**Comment by tuxdna** [comment]
I am observing this error when doing `make test` with a TLS enabled docker daemon:

```
export DOCKER_HOST=tcp://127.0.0.1:2375
export DOCKER_CERT_PATH=$HOME/.docker/local-certs/
export DOCKER_TLS_VERIFY=1
```

```
$ make test

... OUTPUT SKIPPED...

======================================================================
ERROR: test_image_by_name (test_util.TestAtomicUtil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saleem/cdk/atomic/tests/unit/test_util.py", line 9, in test_image_by_name
    matches = util.image_by_name('atomic-test-1')
  File "Atomic/util.py", line 46, in image_by_name
    images = c.images(all=False)
  File "/usr/lib/python2.7/site-packages/docker/api/image.py", line 39, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

```

This appears to be a bug related to pydocker:

 * https://github.com/docker/docker-py/issues/465

**Comment by tuxdna** [comment]
The issue with using pydocker is that it depends on python `requests` module. Python `requests` module does not work well with self-signed certificates. 

It is a bit more involved to make `requests` work with self-signed certificates by passing ca certificate files into method calls, or by installing `certifi` module. None of which looks good to me for a simple self-signed certificates setup.


 * http://docs.python-requests.org/en/latest/user/advanced/#ca-certificates

**Comment by tuxdna** [comment]
@rhatdan  

 * I understand that event with TLS setup, we will not be in situation that Docker actually logs all the actions. 
 * Python Docker / Requests module make it very tough to work with self-signed certificates. Therefore it is not intuitive right now for quick setups.

So I am putting this issue on hold, until I have better ideas.

**Comment by willmtemple** [comment]
@tuxdna I see the primary problem with running them as root being that if I or anyone else bungled something in the test scripts then they could eat your filesystem.

As far as enabling TLS and remote access on your docker daemon: anyone with access to the daemon is effectively root, so gaining access to the docker socket should be considered equivalent to becoming root. Enabling TLS on your daemon and exposing it to the network is the same (basically) as allowing remote users to log in as root with an ssh key.

You can also run docker without becoming root by adding yourself to the `docker` group, but this should be considered equivalent to making yourself a sudoer with no password requirement. We can't test mount on a remote server anyway, so I think the utility of doing testing on remote docker servers without just uploading and running the tests on that server is limited.

@rhatdan I don't like running the tests as root either, but nearly every test requires access to the socket. I could write a patch for the test scripts to temporarily drop privilege using seteuid() and then reclaim privilege before interfacing with atomic. That way we don't call every single command in the scripts as root, only the necessary parts. Talking to docker doesn't require bona fide root, but many of the functions in the mount system (devicemapper integration, to name one) *do* require euid=0, so simply being in the docker group won't suffice.

**Comment by rhatdan** [comment]
atomic test is designed to run as root.  We would need to rework most of the tests to handle not running as root, and for little advantage, since as Will describes access to the docker.sock or docker listening on a network socket is equivalent to root.  

If you are overly concerned about running the test, then you should probably run it in a VM.

atomic migrate, atomic mount atomic scan all would require at least root,
