### ISSUE TITLE
atomic pull errors

### ISSUE THREAD

**Issue by aveshagarwal** [projectatomic/atomic#587]
Just update to latest git master and I see when pulling local docker images:

```
 ./atomic pull docker:etcd
Image docker:etcd is being pulled to ostree ...
./atomic pull docker:etcd: too few arguments
Try './atomic pull docker:etcd --help' for more information.
```

It was working before I updated just now.
@giuseppe

**Comment by giuseppe** [comment]
I cannot reproduce it, could you please attach the output for "./atomic --debug pull docker:etcd"?

**Comment by aveshagarwal** [comment]
```
# ./atomic --debug pull docker:etcd
Image docker:etcd is being pulled to ostree ...
./atomic --debug pull docker:etcd: too few arguments
Try './atomic --debug pull docker:etcd --help' for more information.
Traceback (most recent call last):
  File "./atomic", line 184, in <module>
    sys.exit(_func())
  File "/root/upstream-code/gocode/src/github.com/projectatomic/atomic/Atomic/pull.py", line 16, in pull_image
    super(Pull, self).pull_image()
  File "/root/upstream-code/gocode/src/github.com/projectatomic/atomic/Atomic/syscontainers.py", line 149, in pull_image
    handler(self.args.image)
  File "/root/upstream-code/gocode/src/github.com/projectatomic/atomic/Atomic/syscontainers.py", line 143, in <lambda>
    handlers = {"ostree" : lambda img: self._pull_image_to_ostree(self._get_ostree_repo(), img, True)}
  File "/root/upstream-code/gocode/src/github.com/projectatomic/atomic/Atomic/syscontainers.py", line 136, in _pull_image_to_ostree
    self._pull_docker_image(repo, image.replace("docker:", ""))
  File "/root/upstream-code/gocode/src/github.com/projectatomic/atomic/Atomic/syscontainers.py", line 858, in _pull_docker_image
    return self._pull_docker_tar(repo, temptar.name)
  File "/root/upstream-code/gocode/src/github.com/projectatomic/atomic/Atomic/syscontainers.py", line 874, in _pull_docker_tar
    self._pull_dockertar_layers(repo, imagebranch, temp_dir, input_layers)
  File "/root/upstream-code/gocode/src/github.com/projectatomic/atomic/Atomic/syscontainers.py", line 1014, in _pull_dockertar_layers
    SystemContainers._import_layers_into_ostree(repo, imagebranch, manifest, layers_to_import)
  File "/root/upstream-code/gocode/src/github.com/projectatomic/atomic/Atomic/syscontainers.py", line 818, in _import_layers_into_ostree
    repo.prepare_transaction()
AttributeError: 'NoneType' object has no attribute 'prepare_transaction'
```

**Comment by giuseppe** [comment]
hm.. it seems something is missing, do you have OSTree and python-gobject-base installed?

**Comment by aveshagarwal** [comment]
So I am seeing this issue on rhel 7.3 beta but not on fedora 24.

**Comment by giuseppe** [comment]
you'll probably need to manually install OSTree there

**Comment by rhatdan** [comment]
We need a clean failure then, I thought we checked if OSTree was present?

**Comment by giuseppe** [comment]
yes, we just miss that for "pull" when storage is OSTree, I am adding it right now

**Comment by giuseppe** [comment]
I verified that I get the same error message if I uninstall ostree

**Comment by aveshagarwal** [comment]
@giuseppe Yes installing ostree and its dependencies on 7.3 beta helped and the error did not occur. But the error message was really misleading.
