### ISSUE TITLE
atomic error should be more descriptive if docker daemon is not running

### ISSUE THREAD

**Issue by ddarrah** [projectatomic/atomic#655]
```
[root@signing_7 yum.repos.d]# atomic --debug pull docker.io/busybox
Image docker.io/busybox is being pulled to docker ...
('Connection aborted.', error(2, 'No such file or directory'))
Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/pull.py", line 54, in pull_image
    handler()
  File "/usr/lib/python2.7/site-packages/Atomic/pull.py", line 30, in pull_docker_image
    insecure = True if is_insecure_registry(self.d.info()['RegistryConfig'], strip_port(registry)) else False
  File "/usr/lib/python2.7/site-packages/Atomic/client.py", line 63, in newfunc
    raise e
ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
[root@signing_7 yum.repos.d]# atomic pull docker.io/busybox
Image docker.io/busybox is being pulled to docker ...
('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by baude** [comment]
[bbaude@localhost atomic (master)]$ sudo ./atomic pull docker.io/busybox
Image docker.io/busybox is being pulled to docker ...
The docker daemon does not appear to be running.

[bbaude@localhost atomic (master)]$ sudo ./atomic --version
1.13.0-devel

Better?

**Comment by rhatdan** [comment]
Yes I would say this is fixed in the next release.
