### ISSUE TITLE
"[Errno -2] Name or service not known" during atomic install

### ISSUE THREAD

**Issue by mike-nguyen** [projectatomic/atomic#674]
This issue seems like the same issue as #650.  The atomic install command will pull the image if it is not already downloaded but seems to take a different code path (than atomic pull) that does not have the fix.  If I use the fully qualified image path it pulls with no issues.

busybox has no INSTALL label so the atomic install command doesn't do anything.  It is just used to demonstrate the pull error.  The cockpit/ws container has the INSTALL label.  I separated the pull and install to demonstrate that the atomic pull works without the fully qualified container name.

```
# rpm -qa | grep -e ^atomic -e skopeo
skopeo-1.14-7d786d11d668f2932e524da53afb658438c8ebfc.0aa48eb05ef9b646ac444ddc878eb93dbd3d6d98.el7.centos.x86_64
atomic-1.12.5.7-d7af4a1307d01f48d3f03739e944ef460b066255.c6c664b91e099b3f2078e562af19220c2ff7562d.el7.centos.x86_64
# atomic install busybox
[Errno -2] Name or service not known
# atomic install cockpit/ws
[Errno -2] Name or service not known
# sudo atomic install docker.io/busybox
Getting image source manifest
Getting image source configuration
Uploading blob sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749
 0 B / 1.42 KB [---------------------------------------------------------------]
Uploading blob sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f
 0 B / 651.94 KB [-------------------------------------------------------------]
Uploading manifest to image destination
Storing signatures
 651.94 KB / 651.94 KB [=======================================================]
# atomic pull cockpit/ws
Image cockpit/ws is being pulled to docker ...
Getting image source manifest
Getting image source configuration
Uploading blob sha256:ee0a90cfdf4505d355a25350e4a4dbd891a41b51229ba77262dd0630cfa76735
 0 B / 6.65 KB [---------------------------------------------------------------]
Uploading blob sha256:c46df4a5b63bb61e1602168743fc52dc0656de63d48b97d5983b980c60ca3a19
 61.22 MB / 64.10 MB [======================================================>--]
Uploading blob sha256:99ef0b2c848550b7648955df8ad94402161af7a899ad52633aa42683e2d891a6
 169.87 MB / 176.53 MB [====================================================>--]
Uploading blob sha256:59a5aa6b0031607119d507be912112fd93701dfa4a5b42cf321ef68a504aab47
 0 B / 8.15 MB [---------------------------------------------------------------]
Uploading blob sha256:5951d07fb74841da3d059ef481fea3525050516cd60c1bf1062fb72c2146771b
 0 B / 150 B [-----------------------------------------------------------------]
Uploading blob sha256:5f76b08ca3d3013ab4ac296cebb30c2e4a9ebe5798f28b7695a2b41447d578e2
 0 B / 785 B [-----------------------------------------------------------------]
Uploading blob sha256:29128c9a04f7e3ecfa650d385b222e6381affc3c497a807b7a05245e1d994cf4
 0 B / 469 B [-----------------------------------------------------------------]
Uploading blob sha256:681bb27149fab85d6b7e4f8dd5dd0e2158d4f55c4753f3e558335a23734c5264
 0 B / 417 B [-----------------------------------------------------------------]
Uploading blob sha256:078f3e27924945f0470a0630688c5180c6ec4627c1b256d0e8e572098d644c5f
 0 B / 778 B [-----------------------------------------------------------------]
Uploading blob sha256:080f6c78b22eca8a23f588d5a2566118d039c73457f8c2d9011ff5b698f698c2
 0 B / 464 B [-----------------------------------------------------------------]
Uploading blob sha256:d174142110f64bb00f772c366ce7963ee88ca8defa22236cd4381c00aeece9c7
 0 B / 413 B [-----------------------------------------------------------------]
Uploading blob sha256:2599a2377ecad4b435fa7099d13eb0aecb224d7a9ea02ea4ea8f20b08f7bcb69
 0 B / 180 B [-----------------------------------------------------------------]
Uploading manifest to image destination
Storing signatures
 180 B / 180 B [===============================================================]-bash-4.2# 
-bash-4.2# atomic install cockpit/ws
/usr/bin/docker run -ti --rm --privileged -v /:/host cockpit/ws /container/atomic-install
+ sed -e /pam_selinux/d -e /pam_sepermit/d /etc/pam.d/cockpit
+ mkdir -p /host/etc/cockpit/ws-certs.d
+ chmod 755 /host/etc/cockpit/ws-certs.d
+ chown root:root /host/etc/cockpit/ws-certs.d
+ mkdir -p /host/var/lib/cockpit
+ chmod 775 /host/var/lib/cockpit
+ chown root:wheel /host/var/lib/cockpit
+ /bin/mount --bind /host/etc/cockpit /etc/cockpit
+ /usr/sbin/remotectl certificate --ensure
```

**Comment by baude** [comment]
Yes, this is because of the changes being implemented wrt skopeo.  I have a large set of code to import eventually that should resolve most of these problems.  Leaving this open until then.

**Comment by mike-nguyen** [comment]
:+1:

**Comment by miabbott** [comment]
We are also seeing this error with fully qualified registry names on the CAHC stream.

```
# rpm-ostree status
State: idle
Deployments:
● centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.368 (2016-10-06 18:12:01)
        Commit: e1f36e1c2a6324a2f598682253766e5f4927e536e5d57057eafe77169e6d797e
        OSName: centos-atomic-host

  centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.366 (2016-10-06 15:07:52)
        Commit: 26f646dfa98697e4913a568ec2d357002d0468d2fbb26cc4c787238313e1fc1a
        OSName: centos-atomic-host
# rpm -q atomic skopeo
atomic-1.12.5.20-f596f1205ae797b7053aed196ee6100a4439af49.c6c664b91e099b3f2078e562af19220c2ff7562d.el7.centos.x86_64
skopeo-1.14-7d786d11d668f2932e524da53afb658438c8ebfc.0aa48eb05ef9b646ac444ddc878eb93dbd3d6d98.el7.centos.x86_64
# atomic --debug install registry.access.redhat.com/rhel7/openscap
[Errno -5] No address associated with hostname
Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/install.py", line 90, in install
    self._check_if_image_present()
  File "/usr/lib/python2.7/site-packages/Atomic/install.py", line 113, in _check_if_image_present
    self.update()
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 115, in update
    util.is_insecure_registry(self.d.info()['RegistryConfig'], util.strip_port(registry)))
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 714, in is_insecure_registry
    for r in get_ips_from_host(registry):
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 708, in get_ips_from_host
    return list(set([x[4][0] for x in socket.getaddrinfo(_host, None)]))
gaierror: [Errno -5] No address associated with hostname
```

**Comment by miabbott** [comment]
As noted in #685, we are seeing this same error using FQDN

```
# atomic --debug install registry.access.redhat.com/rhel7/openscap
[Errno -2] Name or service not known
Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/install.py", line 90, in install
    self._check_if_image_present()
  File "/usr/lib/python2.7/site-packages/Atomic/install.py", line 113, in _check_if_image_present
    self.update()
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 115, in update
    util.is_insecure_registry(self.d.info()['RegistryConfig'], util.strip_port(registry)))
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 714, in is_insecure_registry
    for r in get_ips_from_host(registry):
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 708, in get_ips_from_host
    return list(set([x[4][0] for x in socket.getaddrinfo(_host, None)]))
gaierror: [Errno -2] Name or service not known

# rpm-ostree status
State: idle
Deployments:
● centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.369 (2016-10-06 19:09:47)
        Commit: a136796d6f55f2bf645bc256cee0869ceba12f37d64e104c4195422f92717aa8
        OSName: centos-atomic-host

  centos-atomic-host:centos-atomic-host/7/x86_64/standard
       Version: 7.20160818 (2016-08-18 14:28:07)
        Commit: 709bfd3c4d9274c32bc3b691d642a3f95431136ec1a6b32e4cd5a13764647ba1
        OSName: centos-atomic-host
  GPGSignature: 1 signature
                Signature made Thu 18 Aug 2016 02:39:07 PM UTC using RSA key ID F17E745691BA8335
                Good signature from "CentOS Atomic SIG <security@centos.org>"

# rpm -q atomic skopeo
atomic-1.12.5.20-f596f1205ae797b7053aed196ee6100a4439af49.c6c664b91e099b3f2078e562af19220c2ff7562d.el7.centos.x86_64
skopeo-1.14-7d786d11d668f2932e524da53afb658438c8ebfc.0aa48eb05ef9b646ac444ddc878eb93dbd3d6d98.el7.centos.x86_64
```

**Comment by cgwalters** [comment]
This is blocking a new release of [CAHC](https://wiki.centos.org/SpecialInterestGroup/Atomic/Devel).

**Comment by cgwalters** [comment]
I also get:
```
# atomic run docker.io/centos/tools
...snip stuff about uploading (why does it say uploading?)...
FATA[0128] Error committing the finished image: Error saving image to docker engine: Error response from daemon: invalid tag "docker.io/centos/tools" 
```

**Comment by rhatdan** [comment]
Does this work with the master branch?

**Comment by cgwalters** [comment]
Master branch of what?  You can see the configuration here:

 - skopeo: https://github.com/CentOS/sig-atomic-buildscripts/blob/master/overlay.yml#L79
 - https://github.com/CentOS/sig-atomic-buildscripts/blob/master/overlay.yml#L75

**Comment by baude** [comment]
@cgwalters the uploading bits is a known issue.  Mitr has it on his list.  
Dan, I believe the PR regarding inspect fixes this issue.

**Comment by miabbott** [comment]
The changes in PR #687 address this issue.  I tested the failing cases successfully using @baude's branch.

**Comment by baude** [comment]
Can someone verify this is fixed in the latest master branch and close if so?

**Comment by rhatdan** [comment]
Atomic 1.13 should have this fix.
