### ISSUE TITLE
'No address associated with hostname' when using FQDN during 'atomic install'

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#685]
Saw this testing against the CAHC stream:

```
# rpm-ostree status
State: idle
Deployments:
● centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.368 (2016-10-06 18:12:01)
        Commit: e1f36e1c2a6324a2f598682253766e5f4927e536e5d57057eafe77169e6d797e
        OSName: centos-atomic-host

  centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.366 (2016-10-06 15:07:52)
        Commit: 26f646dfa98697e4913a568ec2d357002d0468d2fbb26cc4c787238313e1fc1a
        OSName: centos-atomic-host
# rpm -q atomic skopeo
atomic-1.12.5.20-f596f1205ae797b7053aed196ee6100a4439af49.c6c664b91e099b3f2078e562af19220c2ff7562d.el7.centos.x86_64
skopeo-1.14-7d786d11d668f2932e524da53afb658438c8ebfc.0aa48eb05ef9b646ac444ddc878eb93dbd3d6d98.el7.centos.x86_64
# atomic --debug install registry.access.redhat.com/rhel7/openscap
[Errno -5] No address associated with hostname
Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/install.py", line 90, in install
    self._check_if_image_present()
  File "/usr/lib/python2.7/site-packages/Atomic/install.py", line 113, in _check_if_image_present
    self.update()
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 115, in update
    util.is_insecure_registry(self.d.info()['RegistryConfig'], util.strip_port(registry)))
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 714, in is_insecure_registry
    for r in get_ips_from_host(registry):
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 708, in get_ips_from_host
    return list(set([x[4][0] for x in socket.getaddrinfo(_host, None)]))
gaierror: [Errno -5] No address associated with hostname

# host registry.access.redhat.com
registry.access.redhat.com is an alias for registry-access-redhat-com.edge.prod.ext.phx2.redhat.com.
registry-access-redhat-com.edge.prod.ext.phx2.redhat.com has address 10.4.164.31
```

**Comment by miabbott** [comment]
Strange.  This error is returned when using CAHC on a Vagrant box on my system, but in an OpenStack VM, I get the error from #674 

I'm going to close this and comment further over there.
