### ISSUE TITLE
'atomic install' not parsing registry hostname correctly

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#688]
This is affecting the CAHC stream currently.

When using `atomic install` with `registry.access.redhat.com`, the command appears to be appending `docker.io` to the beginning of the image string before trying to use `skopeo` to retrieve it.

```
-bash-4.2# rpm-ostree status
State: idle
Deployments:
● centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.407 (2016-10-10 05:12:09)
        Commit: f8760346744bd1ff92b9ed97c92aa10927fb22ed9f50e743089d40d6fb27aa29
        OSName: centos-atomic-host

  centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.382 (2016-10-07 21:13:33)
        Commit: e78e6e68d6a3714c2617f5002ade42bdcd29b9f07e984335f7558df47adb7000
        OSName: centos-atomic-host
-bash-4.2# rpm -q atomic skopeo
atomic-1.13.0.0-71d0ccbb2abff9faaa99e18afb9aacff596678aa.c6c664b91e099b3f2078e562af19220c2ff7562d.el7.centos.x86_64
skopeo-1.14-7d786d11d668f2932e524da53afb658438c8ebfc.0aa48eb05ef9b646ac444ddc878eb93dbd3d6d98.el7.centos.x86_64
-bash-4.2# atomic install registry.access.redhat.com/rhel7/openscap
Trying docker.io/registry.access.redhat.com/rhel7/openscap:latest
Unable to resolve registry.access.redhat.com/rhel7/openscap
-bash-4.2# atomic install registry.access.redhat.com/rhel7/openscap
Trying docker.io/registry.access.redhat.com/rhel7/openscap:latest
Unable to resolve registry.access.redhat.com/rhel7/openscap
-bash-4.2# atomic --debug install registry.access.redhat.com/rhel7/openscap                                                                                                                                        
[
    {
        "search": true,
        "hostname": "registry-1.docker.io",
        "name": "docker.io",
        "secure": true
    }
]
Trying docker.io/registry.access.redhat.com/rhel7/openscap:latest
URL: https://registry-1.docker.io/v2/
GET_URL: https://registry-1.docker.io/v2/
GET_HEADER: {'Accept': '[application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribut
ion.manifest.v1+json]'}
GET_VERIFY: True
Set token_scope to repository:registry.access.redhat.com/rhel7/openscap:pull
URL: http://registry-1.docker.io/v2/
GET_URL: https://auth.docker.io/token?service=registry.docker.io&scope=repository:registry.access.redhat.com/rhel7/openscap:pull
GET_HEADER: {'Accept': '[application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribut
ion.manifest.v1+json]'}
GET_VERIFY: True
Set token to eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDTHpDQ0FkU2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0Uk5Gb3pPa2RYTjBrNldGUlFSRHBJVFRSUk9rOVVWRmc2TmtGRlF6cFNUVE5ET2tGU01rTTZUMFkzTn
pwQ1ZrVkJPa2xHUlVrNlExazFTekFlRncweE5qQTFNekV5TXpVNE5UZGFGdzB4TnpBMU16RXlNelU0TlRkYU1FWXhSREJDQmdOVkJBTVRPMUV6UzFRNlFqSkpNenBhUjFoT09qSlhXRTA2UTBWWFF6cFVNMHhPT2tvMlYxWTZNbGsyVHpwWlFWbEpPbGhQVTBRNlZFUlJTVG8wVWtwR
E1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVo0NkVLV3VKSXhxOThuUC9GWEU3U3VyOXlkZ3c3K2FkcndxeGlxN004VHFUa0N0dzBQZm1SS2VLdExwaXNTRFU4LzZseWZ3QUFwZWh6SHdtWmxZR2dxT0JzakNCcnpBT0JnTlZIUThCQWY4RUJBTUNCNEF3RHdZRFZS
MGxCQWd3QmdZRVZSMGxBREJFQmdOVkhRNEVQUVE3VVROTFZEcENNa2t6T2xwSFdFNDZNbGRZVFRwRFJWZERPbFF6VEU0NlNqWlhWam95V1RaUE9sbEJXVWs2V0U5VFJEcFVSRkZKT2pSU1NrTXdSZ1lEVlIwakJEOHdQWUE3VVRSYU16cEhWemRKT2xoVVVFUTZTRTAwVVRwUFZGUll
PalpCUlVNNlVrMHpRenBCVWpKRE9rOUdOemM2UWxaRlFUcEpSa1ZKT2tOWk5Vc3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTzYxSWloN1FUcHNTMFFIYUNwTDFZTWNMMnZXZlNydlhHbHpSRDEwN2NRUEFpRUFtZXduelNYRHplRGxqcDc4T1NsTFFzbnROYWM5eHRyYW0xU0kxY0
ZXQ2tJPSJdfQ.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE0NzYxMDg5NjMsImlhdCI6MTQ3NjEwODY2MywiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiI1aXNOVkNrSWViR0l3cXZ2bTBWViIsIm5iZiI6MTQ3NjEwODY2Mywic3ViIj
oiIn0.sPgdjKm4D9aYLFFSuuJfB_MhOrCFm7Sz6i_uxhP-7Jw5BatuV7MvxXuA3q5D0olbR5CN5R4VB3TlGgUfx7jIlQ
GET_URL: http://registry-1.docker.io/v2/
GET_HEADER: {'Authorization': 'Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDTHpDQ0FkU2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0Uk5Gb3pPa2RYTjBrNldGUlFSRHBJVFRSUk9rOVVWRmc2TmtGRlF6c
FNUVE5ET2tGU01rTTZUMFkzTnpwQ1ZrVkJPa2xHUlVrNlExazFTekFlRncweE5qQTFNekV5TXpVNE5UZGFGdzB4TnpBMU16RXlNelU0TlRkYU1FWXhSREJDQmdOVkJBTVRPMUV6UzFRNlFqSkpNenBhUjFoT09qSlhXRTA2UTBWWFF6cFVNMHhPT2tvMlYxWTZNbGsyVHpwWlFWbEpP
bGhQVTBRNlZFUlJTVG8wVWtwRE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVo0NkVLV3VKSXhxOThuUC9GWEU3U3VyOXlkZ3c3K2FkcndxeGlxN004VHFUa0N0dzBQZm1SS2VLdExwaXNTRFU4LzZseWZ3QUFwZWh6SHdtWmxZR2dxT0JzakNCcnpBT0JnTlZIUTh
CQWY4RUJBTUNCNEF3RHdZRFZSMGxCQWd3QmdZRVZSMGxBREJFQmdOVkhRNEVQUVE3VVROTFZEcENNa2t6T2xwSFdFNDZNbGRZVFRwRFJWZERPbFF6VEU0NlNqWlhWam95V1RaUE9sbEJXVWs2V0U5VFJEcFVSRkZKT2pSU1NrTXdSZ1lEVlIwakJEOHdQWUE3VVRSYU16cEhWemRKT2
xoVVVFUTZTRTAwVVRwUFZGUllPalpCUlVNNlVrMHpRenBCVWpKRE9rOUdOemM2UWxaRlFUcEpSa1ZKT2tOWk5Vc3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTzYxSWloN1FUcHNTMFFIYUNwTDFZTWNMMnZXZlNydlhHbHpSRDEwN2NRUEFpRUFtZXduelNYRHplRGxqcDc4T1NsT
FFzbnROYWM5eHRyYW0xU0kxY0ZXQ2tJPSJdfQ.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE0NzYxMDg5NjMsImlhdCI6MTQ3NjEwODY2MywiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiI1aXNOVkNrSWViR0l3cXZ2bTBWViIsIm5iZ
iI6MTQ3NjEwODY2Mywic3ViIjoiIn0.sPgdjKm4D9aYLFFSuuJfB_MhOrCFm7Sz6i_uxhP-7Jw5BatuV7MvxXuA3q5D0olbR5CN5R4VB3TlGgUfx7jIlQ', 'Accept': '[application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.
manifest.v2+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribution.manifest.v1+json]'}
GET_VERIFY: True
URL: http://registry-1.docker.io/v2/
GET_URL: http://registry-1.docker.io/v2/
GET_HEADER: {'Authorization': 'Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDTHpDQ0FkU2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0Uk5Gb3pPa2RYTjBrNldGUlFSRHBJVFRSUk9rOVVWRmc2TmtGRlF6c
FNUVE5ET2tGU01rTTZUMFkzTnpwQ1ZrVkJPa2xHUlVrNlExazFTekFlRncweE5qQTFNekV5TXpVNE5UZGFGdzB4TnpBMU16RXlNelU0TlRkYU1FWXhSREJDQmdOVkJBTVRPMUV6UzFRNlFqSkpNenBhUjFoT09qSlhXRTA2UTBWWFF6cFVNMHhPT2tvMlYxWTZNbGsyVHpwWlFWbEpP
bGhQVTBRNlZFUlJTVG8wVWtwRE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVo0NkVLV3VKSXhxOThuUC9GWEU3U3VyOXlkZ3c3K2FkcndxeGlxN004VHFUa0N0dzBQZm1SS2VLdExwaXNTRFU4LzZseWZ3QUFwZWh6SHdtWmxZR2dxT0JzakNCcnpBT0JnTlZIUTh
CQWY4RUJBTUNCNEF3RHdZRFZSMGxCQWd3QmdZRVZSMGxBREJFQmdOVkhRNEVQUVE3VVROTFZEcENNa2t6T2xwSFdFNDZNbGRZVFRwRFJWZERPbFF6VEU0NlNqWlhWam95V1RaUE9sbEJXVWs2V0U5VFJEcFVSRkZKT2pSU1NrTXdSZ1lEVlIwakJEOHdQWUE3VVRSYU16cEhWemRKT2
xoVVVFUTZTRTAwVVRwUFZGUllPalpCUlVNNlVrMHpRenBCVWpKRE9rOUdOemM2UWxaRlFUcEpSa1ZKT2tOWk5Vc3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTzYxSWloN1FUcHNTMFFIYUNwTDFZTWNMMnZXZlNydlhHbHpSRDEwN2NRUEFpRUFtZXduelNYRHplRGxqcDc4T1NsT
FFzbnROYWM5eHRyYW0xU0kxY0ZXQ2tJPSJdfQ.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE0NzYxMDg5NjMsImlhdCI6MTQ3NjEwODY2MywiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiI1aXNOVkNrSWViR0l3cXZ2bTBWViIsIm5iZ
iI6MTQ3NjEwODY2Mywic3ViIjoiIn0.sPgdjKm4D9aYLFFSuuJfB_MhOrCFm7Sz6i_uxhP-7Jw5BatuV7MvxXuA3q5D0olbR5CN5R4VB3TlGgUfx7jIlQ', 'Accept': '[application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.
manifest.v2+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribution.manifest.v1+json]'}
GET_VERIFY: True
GET_URL: http://registry-1.docker.io/v2/registry.access.redhat.com/rhel7/openscap/manifests/latest
GET_HEADER: {'Authorization': 'Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDTHpDQ0FkU2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0Uk5Gb3pPa2RYTjBrNldGUlFSRHBJVFRSUk9rOVVWRmc2TmtGRlF6c
FNUVE5ET2tGU01rTTZUMFkzTnpwQ1ZrVkJPa2xHUlVrNlExazFTekFlRncweE5qQTFNekV5TXpVNE5UZGFGdzB4TnpBMU16RXlNelU0TlRkYU1FWXhSREJDQmdOVkJBTVRPMUV6UzFRNlFqSkpNenBhUjFoT09qSlhXRTA2UTBWWFF6cFVNMHhPT2tvMlYxWTZNbGsyVHpwWlFWbEpP
bGhQVTBRNlZFUlJTVG8wVWtwRE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVo0NkVLV3VKSXhxOThuUC9GWEU3U3VyOXlkZ3c3K2FkcndxeGlxN004VHFUa0N0dzBQZm1SS2VLdExwaXNTRFU4LzZseWZ3QUFwZWh6SHdtWmxZR2dxT0JzakNCcnpBT0JnTlZIUTh
CQWY4RUJBTUNCNEF3RHdZRFZSMGxCQWd3QmdZRVZSMGxBREJFQmdOVkhRNEVQUVE3VVROTFZEcENNa2t6T2xwSFdFNDZNbGRZVFRwRFJWZERPbFF6VEU0NlNqWlhWam95V1RaUE9sbEJXVWs2V0U5VFJEcFVSRkZKT2pSU1NrTXdSZ1lEVlIwakJEOHdQWUE3VVRSYU16cEhWemRKT2
xoVVVFUTZTRTAwVVRwUFZGUllPalpCUlVNNlVrMHpRenBCVWpKRE9rOUdOemM2UWxaRlFUcEpSa1ZKT2tOWk5Vc3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTzYxSWloN1FUcHNTMFFIYUNwTDFZTWNMMnZXZlNydlhHbHpSRDEwN2NRUEFpRUFtZXduelNYRHplRGxqcDc4T1NsT
FFzbnROYWM5eHRyYW0xU0kxY0ZXQ2tJPSJdfQ.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE0NzYxMDg5NjMsImlhdCI6MTQ3NjEwODY2MywiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiI1aXNOVkNrSWViR0l3cXZ2bTBWViIsIm5iZ
iI6MTQ3NjEwODY2Mywic3ViIjoiIn0.sPgdjKm4D9aYLFFSuuJfB_MhOrCFm7Sz6i_uxhP-7Jw5BatuV7MvxXuA3q5D0olbR5CN5R4VB3TlGgUfx7jIlQ', 'Accept': '[application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.
manifest.v2+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribution.manifest.v1+json]'}
GET_VERIFY: True
Unable to resolve registry.access.redhat.com/rhel7/openscap
Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/install.py", line 90, in install
    self._check_if_image_present()
  File "/usr/lib/python2.7/site-packages/Atomic/install.py", line 113, in _check_if_image_present
    self.update()
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 113, in update
    fq_name = self.get_fq_image_name(self.image)
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 713, in get_fq_image_name
    return ri.find_image_on_registry()
  File "/usr/lib/python2.7/site-packages/Atomic/discovery.py", line 287, in find_image_on_registry
    raise RegistryInspectError("Unable to resolve {}".format(self.orig_input))
RegistryInspectError: Unable to resolve registry.access.redhat.com/rhel7/openscap
```

**Comment by rhatdan** [comment]
@miabbott Have you checked against master branch?

**Comment by miabbott** [comment]
@rhatdan `atomic` is built from git master on CAHC:

```
# rpm -q atomic 
atomic-1.13.0.0-71d0ccbb2abff9faaa99e18afb9aacff596678aa.c6c664b91e099b3f2078e562af19220c2ff7562d.el7.centos.x86_64
```

I believe `71d0ccbb2abff9faaa99e18afb9aacff596678aa` is HEAD of master

**Comment by rhatdan** [comment]
Ok thanks.

**Comment by rhatdan** [comment]
@baude Looks like it is your new stuff.

**Comment by baude** [comment]
@miabbott this should be fixed in master, mind verifying?

**Comment by rhatdan** [comment]
I am about to cut atomic-1.13.1 So should be fixed there.  But verifying the master would be good.

**Comment by miabbott** [comment]
Tested with master and this test case works.  (The schema error is known and specific to that registry/image)

```
# git rev-parse HEAD
4445c411f2e7f7bc5b40f43902e3759229511cd3
# ./atomic --version
1.13.1
# ./atomic install registry.access.redhat.com/rhel7/openscap
Getting image source manifest
Getting image source configuration
Uploading blob sha256:30cf2e26a24f2a8426cbe8444f8af2ecb7023bd468b05c1b6fd0b2797b0f9ff9
 67.95 MB / ? [------------------------------------------=--------------------] 
Uploading blob sha256:99dd41655d8a45c2fb74f9eeb73e327b3ad4796f0ff0d602c575e32e9804baed
 0 B / ? [--------------------------------------------------------------------=]
Uploading blob sha256:d830c1ce8754afc306dc9969a5504f8571519afb65c09bca9a90b87955909868
 29.87 MB / ? [------------------=--------------------------------------------] 
Uploading manifest to image destination
FATA[0019] Error writing manifest: Unsupported manifest type, need a Docker schema 2 manifest 
```
