### ISSUE TITLE
Exceptions when trying to list containers 

### ISSUE THREAD

**Issue by yunchih** [projectatomic/atomic#749]
On a clean install of Atomic-Fedora, after pulling and installing an container with the following commands:

```
sudo atomic pull gscrivano/etcd
sudo atomic install --system gscrivano/etcd
```

I got an exception when executing `atomic containers list`.

```
[fedora@atomic01 ~]$ sudo atomic images list
   REPOSITORY       TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   gscrivano/etcd   latest   4736d82a3b17   2016-11-05 00:43   246.53 MB      Docker    
>  gscrivano/etcd   latest   1bf057249337   2016-11-06 02:57                  system    

[fedora@atomic01 ~]$ sudo atomic --debug containers list 
a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.5/site-packages/Atomic/containers.py", line 88, in ps_tty
    info = self.syscontainers.get_container_runtime_info(container)
  File "/usr/lib/python3.5/site-packages/Atomic/syscontainers.py", line 590, in get_container_runtime_info
    if self._is_service_active(container):
  File "/usr/lib/python3.5/site-packages/Atomic/syscontainers.py", line 688, in _is_service_active
    return self._systemctl_command("is-active", name, quiet=True).replace("\n", "") == "active"
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/atomic", line 212, in <module>
    sys.exit(1)
SystemExit: 1
[fedora@atomic01 ~]$ atomic --version
1.13.1
[fedora@atomic01 ~]$ atomic host status
State: idle
Deployments:
● fedora-atomic:fedora-atomic/24/x86_64/docker-host
       Version: 24.75 (2016-11-06 02:21:39)
    BaseCommit: 7abaffc73e4407790827a7779763ceb5581ca4cfa5129ce8488f10212463964c
        Commit: ec90bc46bfc24ca2162efe257f4afd74a622a174566a3b0fb396aabb1d3df408
        OSName: fedora-atomic
      Packages: htop parted

  fedora-atomic:fedora-atomic/24/x86_64/docker-host
       Version: 24.75 (2016-11-05 06:54:35)
        Commit: 7abaffc73e4407790827a7779763ceb5581ca4cfa5129ce8488f10212463964c
        OSName: fedora-atomic
```

**Comment by jlebon** [comment]
This should be fixed in v1.13.2 by https://github.com/projectatomic/atomic/commit/b227b2a8b355da7989124e228e3c6bd57e07ec00.
