### ISSUE TITLE
atomic cli fails in absence of python-dateutil package - CentOS

### ISSUE THREAD

**Issue by dharmit** [projectatomic/atomic#804]
On a freshly setup and updated CentOS system, `atomic` cli fails with following traceback:

~~~shell
$ atomic
Traceback (most recent call last):
  File "/usr/bin/atomic", line 44, in <module>
    from Atomic import containers
  File "/usr/lib/python2.7/site-packages/Atomic/containers.py", line 9, in <module>
    from dateutil.parser import parse as dateparse
ImportError: No module named dateutil.parser

$ atomic scan --list
Traceback (most recent call last):
  File "/usr/bin/atomic", line 44, in <module>
    from Atomic import containers
  File "/usr/lib/python2.7/site-packages/Atomic/containers.py", line 9, in <module>
    from dateutil.parser import parse as dateparse
ImportError: No module named dateutil.parser

$ atomic -v
Traceback (most recent call last):
  File "/usr/bin/atomic", line 44, in <module>
    from Atomic import containers
  File "/usr/lib/python2.7/site-packages/Atomic/containers.py", line 9, in <module>
    from dateutil.parser import parse as dateparse
ImportError: No module named dateutil.parser

$ atomic --help
Traceback (most recent call last):
  File "/usr/bin/atomic", line 44, in <module>
    from Atomic import containers
  File "/usr/lib/python2.7/site-packages/Atomic/containers.py", line 9, in <module>
    from dateutil.parser import parse as dateparse
ImportError: No module named dateutil.parser

$ rpm -qa | grep atomic
atomic-1.13.8-1.el7.x86_64
~~~

After doing `yum -y install python-dateutil` it starts functioning without any issues. Should the package be a dependency that automatically gets installed when you do `yum -y install atomic`?

**Comment by navidshaikh** [comment]
Should be SPEC file update for atomic package, the mentioned package is listed in [requirements.txt](https://github.com/projectatomic/atomic/blob/master/requirements.txt#L8)

**Comment by rhatdan** [comment]
> rpm -q --requires atomic | grep date
python3-dateutil
> rpm -q atomic
atomic-1.14.1-1.fc26.x86_64

Should be in the next release.

**Comment by dharmit** [comment]
Any plan to support Python 2?

**Comment by rhatdan** [comment]
Yes for RHEL7 and Centos7 this will be supported.

**Comment by baude** [comment]
What is the status of this issue?

**Comment by navidshaikh** [comment]
For 
```
$ rpm -q atomic
atomic-1.20.1-9.git436cf5d.el7.centos.x86_64
```

on
```
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

atomic now installs `python-dateutils`

```
$ repoquery --requires atomic
/bin/bash
/usr/bin/python2
PyYAML
container-storage-setup
dbus
gomtree
ostree
polkit
python(abi) = 2.7
python-dateutil
python-dbus
python-docker-py >= 1.7.2-1
python-ipaddress
python-requests
python-setuptools
python-six >= 1.3.0
python-slip-dbus
python-websocket-client >= 0.11.0
rpm-python
runc
setup
skopeo >= 1:0.1.24-1.dev
skopeo-containers >= 1:0.1.24-1.dev
```
