### ISSUE TITLE
1.14.1, "atomic storage" broken

### ISSUE THREAD

**Issue by mvollmer** [projectatomic/atomic#805]
With atomic 1.1.4.1, none of the "atomic storage" commands seem to work:

```
# atomic storage reset
/usr/bin/atomic storage reset: too few arguments
Try '/usr/bin/atomic storage reset --help' for more information.
```

Adding `--debug` shows the culprit:

```
# atomic --debug storage reset
/usr/bin/atomic --debug storage reset: too few arguments
Try '/usr/bin/atomic --debug storage reset --help' for more information.
Traceback (most recent call last):
  File "/usr/bin/atomic", line 184, in <module>
    _class = atomic if '_class' not in args else args._class() # pylint: disable=protected-access
  File "/usr/lib/python3.5/site-packages/Atomic/storage.py", line 120, in __init__
    if self.args.graph:
AttributeError: 'NoneType' object has no attribute 'graph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 201, in <module>
    aparser.print_usage()
  File "/usr/bin/atomic", line 79, in print_usage
    self.error(message)
  File "/usr/bin/atomic", line 75, in error
    sys.exit(2)
SystemExit: 2
```

**Comment by mvollmer** [comment]
43fc70035a308 looks very fishy

**Comment by mvollmer** [comment]
This regression was found by the Cockpit integration tests.  Would be nice to catch this earlier, and `atomic` itself has tests for the `Storage` class, no? Did they pass somehow?

**Comment by mvollmer** [comment]
#806 should help reduce the confusion, but it only improves the message, not the regression.
