### ISSUE TITLE
'atomic images verify' returns argument error with certain images

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#813]
Using `atomic 1.14.1`, an argument error is returned when trying to use `atomic images verify` on certain images.  I suspect it is a problem verifying images from v1 registries, but I'll let the experts hash it out.

For example, using `atomic images verify` on an image from docker.io returns successfully:

```
# atomic pull docker.io/nginx
Image docker.io/nginx is being pulled to docker ...
Pulling docker.io/library/nginx:latest ...
Copying blob sha256:75a822cd7888e394c49828b951061402d31745f596b1f502758570f2d0ee79e2
 48.91 MB / 48.98 MB [=========================================================]
Copying blob sha256:0aefb9dc4a57d3de6a9cfa2e87e4502dfa8ce3876264bb20783b1610f8e44806
 19.22 MB / 19.24 MB [=========================================================]
Copying blob sha256:046e44ee6057f1264d00b0c54adcff2f2c44d30a29b50dfef928776f7aa45cc8
 0 B / 193 B [-----------------------------------------------------------------]
Copying config sha256:01f818af747d88b4ebca7cdabd0c581e406e0e790be72678d257735fad84a15f
 0 B / 3.62 KB [---------------------------------------------------------------]
Writing manifest to image destination
Storing signatures
 3.62 KB / 3.62 KB [===========================================================]
# atomic images list
   REPOSITORY        TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   docker.io/nginx   latest   01f818af747d   2016-12-27 17:56   181.59 MB      docker    

# atomic images verify docker.io/nginx
# echo $?
0
```

However, running the same command on an image from registry.access.redhat.com returns the argument error.

```
# atomic pull registry.access.redhat.com/rhel7
Image registry.access.redhat.com/rhel7 is being pulled to docker ...
Pulling registry.access.redhat.com/rhel7:latest ...
Copying blob sha256:f9ab7164e76a8a165fce660638966566d3a4cb9dc8b63892f784acd4d1c7b9f3
 68.72 MB / ? [---------=-----------------------------------------------------] 
Copying blob sha256:d77ab047cab88f266864ed80af55249d37a06379b4bd1afef555996259bc819f
 0 B / ? [--------------------------------------------------------------------=]
Copying config sha256:e8e3aaf82af53563382e4079d833ebeda12f65a7afb9ab98345decbceece7e20
 0 B / 4.51 KB [---------------------------------------------------------------]
Writing manifest to image destination
Storing signatures
 4.51 KB / 4.51 KB [===========================================================]
# atomic images list
   REPOSITORY                         TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   docker.io/nginx                    latest   01f818af747d   2016-12-27 17:56   181.59 MB      docker    
   registry.access.redhat.com/rhel7   latest   e8e3aaf82af5   2016-11-30 22:16   192.53 MB      docker    

# atomic images verify registry.access.redhat.com/rhel7
/bin/atomic images verify registry.access.redhat.com/rhel7: too few arguments
Try '/bin/atomic images verify registry.access.redhat.com/rhel7 --help' for more information.
# echo $?
2
```

**Comment by miabbott** [comment]
```
# atomic --debug images verify registry.access.redhat.com/rhel7
Namespace(_class=<class 'Atomic.verify.Verify'>, assumeyes=False, debug=True, func='verify', image='registry.access.redhat.com/rhel7', no_validate=False, storage='docker', verbose=False)
/bin/atomic --debug images verify registry.access.redhat.com/rhel7: too few arguments
Try '/bin/atomic --debug images verify registry.access.redhat.com/rhel7 --help' for more information.
Traceback (most recent call last):
  File "/bin/atomic", line 187, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/verify.py", line 63, in verify
    local_layers, remote_layers = self._verify()
  File "/usr/lib/python2.7/site-packages/Atomic/verify.py", line 91, in _verify
    remote_img_obj = be.make_remote_image(remote_img_name)
  File "/usr/lib/python2.7/site-packages/Atomic/backends/_docker.py", line 162, in make_remote_image
    img_obj.populate_remote_inspect_info()
  File "/usr/lib/python2.7/site-packages/Atomic/objects/image.py", line 136, in populate_remote_inspect_info
    remote_inspect_info = self.remote_inspect()
  File "/usr/lib/python2.7/site-packages/Atomic/objects/image.py", line 153, in remote_inspect
    inspect_info['id'] = ri.rc.manifest_json.get("config", None).get("digest", None)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by baude** [comment]
Fixed in https://github.com/projectatomic/atomic/commit/1c16902b1568f1ba397d5df2d254a6fbda744fb2
