### ISSUE TITLE
invalid regular expression when parsing registry names for 'atomic trust'

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#821]
It appears that #819 broke things

```
# ./atomic --debug trust add -t insecureAcceptAnything registry.access.redhat.com
nothing to repeat
Traceback (most recent call last):
  File "./atomic", line 188, in <module>
    sys.exit(_func())
  File "/var/atomic/Atomic/trust.py", line 108, in add
    util.is_valid_image_uri(registry)
  File "/var/atomic/Atomic/util.py", line 754, in is_valid_image_uri
    registry_pattern = re.compile(r'^[a-zA-Z0-9-_\.]+:?([0-9]*)?$')
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
error: nothing to repeat
```

**Comment by rhatdan** [comment]
@aweiteka PTAL

**Comment by miabbott** [comment]
Looks like user error.  Re-tested on clean F25 system and was able to get it working.
