### ISSUE TITLE
'atomic pull' requires v1 registry to be added to /etc/sysconfig/docker

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#844]
While testing #843, we found that using `atomic pull` to retrieve images from a v1 registry required that the registry be added to `/etc/sysconfig/docker` using the `--add-registry` option.

```
# git branch 
  master
* more_run_regressions
# git rev-parse HEAD
f77a3cd13677fedc50cf84c080755857baf7e5d2
# ./atomic pull registry.access.redhat.com/rhel7

# ./atomic --debug pull registry.access.redhat.com/rhel7
Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', image='registry.access.redhat.com/rhel7', reg_type=None, storage='docker')

Traceback (most recent call last):
  File "./atomic", line 188, in <module>
    sys.exit(_func())
  File "/root/atomic/Atomic/pull.py", line 42, in pull_image
    be.pull_image(self.args.image, debug=self.args.debug)
  File "/root/atomic/Atomic/backends/_docker.py", line 221, in pull_image
    remote_image = self.make_remote_image(image)
  File "/root/atomic/Atomic/backends/_docker.py", line 183, in make_remote_image
    img_obj.populate_remote_inspect_info()
  File "/root/atomic/Atomic/objects/image.py", line 150, in populate_remote_inspect_info
    remote_inspect_info = self.remote_inspect()
  File "/root/atomic/Atomic/objects/image.py", line 166, in remote_inspect
    tag=self.tag, orig_input=self.input_name)
  File "/root/atomic/Atomic/discovery.py", line 204, in __init__
    self._setup_rc()
  File "/root/atomic/Atomic/discovery.py", line 212, in _setup_rc
    self.rc.hostname = (x['hostname'] for x in self.registries if x['name'] == self.registry).next()  # pylint: disable=next-method-called
StopIteration
# echo "ADD_REGISTRY='--add-registry registry.access.redhat.com'" >> /etc/sysconfig/docker
# systemctl restart docker
# ./atomic pull registry.access.redhat.com/rhel7
Pulling registry.access.redhat.com/rhel7:latest ...
Copying blob sha256:7bd78273b66657ac8b3e800506047866ce94eea0b50e23ecdb76b0a8fbc5cdcc
 68.77 MB / ? [--------=------------------------------------------------------] 
Copying blob sha256:c196631bd9ac47f0e62cd3b0160159ccf34a88b47a9487a0c3dd3c55b457d607
 0 B / ? [--------------------------------------------------------------------=]
Copying config sha256:e4b79d4d89ab9b0aa873fd8dc99c652483bb645f317712ef30d5904ac2eafef3
 0 B / 4.51 KB [---------------------------------------------------------------]
Writing manifest to image destination
Storing signatures
 1.19 KB / ? [-------------------=--------------------------------------------] 
```

@baude already knows about this, just filing it so it is not lost in the ether

**Comment by miabbott** [comment]
Closed via #843
