### ISSUE TITLE
pull --storage ostree results into "Not a regular file or symlink: loop1 (0)"

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic#943]
This is basically a copy of https://github.com/projectatomic/atomic/pull/767#issuecomment-287818865.

Since I can reproduce with latest release of `atomic`, I am reporting as a new issue.

Environment is Fedora rawhide:

```
$ rpm -q docker atomic ostree
docker-1.13.1-4.git5be1549.fc27.x86_64
atomic-1.15.3-2.fc26.x86_64
ostree-2017.2-3.fc26.x86_64
```

The issue:

```
$ atomic --debug pull --storage ostree docker:modularitycontainers/nginx
Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', image='docker:modularitycontainers/nginx', reg_type=None, storage='ostree')
g-io-error-quark: Not a regular file or symlink: loop1 (0)
Traceback (most recent call last):
  File "/usr/bin/atomic", line 188, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/pull.py", line 53, in pull_image
    be.pull_image(self.args.image, remote_image_obj, debug=self.args.debug, assumeyes=self.args.assumeyes)
  File "/usr/lib/python3.6/site-packages/Atomic/backends/_ostree.py", line 115, in pull_image
    return self.syscontainers.pull_image(image)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 154, in pull_image
    self._pull_image_to_ostree(self._get_ostree_repo(), image or self.args.image, True)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 145, in _pull_image_to_ostree
    image = self._pull_docker_image(repo, image.replace("docker:", "", 1))
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1111, in _pull_docker_image
    return self._pull_docker_tar(repo, temptar.name, image)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1132, in _pull_docker_tar
    self._pull_dockertar_layers(repo, imagebranch, temp_dir, input_layers, labels=labels)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1298, in _pull_dockertar_layers
    self._import_layers_into_ostree(repo, imagebranch, manifest, layers_to_import)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1077, in _import_layers_into_ostree
    repo.write_directory_to_mtree(Gio.File.new_for_path(temp_dir), mtree, modifier)
GLib.GError: g-io-error-quark: Not a regular file or symlink: loop1 (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 210, in <module>
    sys.exit(1)
SystemExit: 1
```

[Dockerfile](https://github.com/container-images/nginx/blob/64c2f087c19f6fb20ab33e8a1ed96e5a5a4e17ab/Dockerfile)

When I run `bash` inside the image with docker, this is what I see in `/dev`:

```
$ docker run -ti modularitycontainers/nginx bash
bash-4.4# cd /dev
bash-4.4# ls -lha
total 0
drwxr-xr-x 5 root root     360 Mar 21 05:01 .
drwxr-xr-x 1 root root      16 Mar 21 05:01 ..
crw------- 1 root root 136, 25 Mar 21 05:01 console
lrwxrwxrwx 1 root root      11 Mar 21 05:01 core -> /proc/kcore
lrwxrwxrwx 1 root root      13 Mar 21 05:01 fd -> /proc/self/fd
crw-rw-rw- 1 root root   1,  7 Mar 21 05:01 full
drwxrwxrwt 2 root root      40 Mar 21 05:01 mqueue
crw-rw-rw- 1 root root   1,  3 Mar 21 05:01 null
lrwxrwxrwx 1 root root       8 Mar 21 05:01 ptmx -> pts/ptmx
drwxr-xr-x 2 root root       0 Mar 21 05:01 pts
crw-rw-rw- 1 root root   1,  8 Mar 21 05:01 random
drwxrwxrwt 2 root root      40 Mar 21 05:01 shm
lrwxrwxrwx 1 root root      15 Mar 21 05:01 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root      15 Mar 21 05:01 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root      15 Mar 21 05:01 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root   5,  0 Mar 21 05:01 tty
crw-rw-rw- 1 root root   1,  9 Mar 21 05:01 urandom
crw-rw-rw- 1 root root   1,  5 Mar 21 05:01 zero
```

This is how `/dev` looks when `atomic` tries to import the image:

```
/var/lib/containers/atomic/.Bze55J $ ll dev
total 0
crw------- 1 root mock  5,   1 Mar  8 19:10 console
lrwxrwxrwx 1 root mock      13 Mar 20 17:28 fd -> /proc/self/fd
crw-rw-rw- 1 root mock  1,   7 Mar  8 19:10 full
brw-rw-rw- 1 root mock  7,   0 Mar  8 19:10 loop0
brw-rw-rw- 1 root mock  7,   1 Mar  8 19:10 loop1
brw-rw-rw- 1 root mock  7,   2 Mar  8 19:10 loop2
brw-rw-rw- 1 root mock  7,   3 Mar  8 19:10 loop3
brw-rw-rw- 1 root mock  7,   4 Mar  8 19:10 loop4
crw-rw-rw- 1 root mock 10, 237 Mar  8 19:10 loop-control
crw-rw-rw- 1 root mock  1,   3 Mar  8 19:10 null
lrwxrwxrwx 1 root mock       8 Mar 20 17:28 ptmx -> pts/ptmx
drwxrwsr-x 2 root mock       6 Mar  8 19:10 pts
crw-rw-rw- 1 root mock  1,   8 Mar  8 19:10 random
drwxrwsr-x 2 root mock       6 Mar  8 19:10 shm
lrwxrwxrwx 1 root mock      15 Mar 20 17:28 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root mock      15 Mar 20 17:28 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root mock      15 Mar 20 17:28 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root tty   5,   0 Mar  8 19:10 tty
cr--r--r-- 1 root mock  1,   9 Mar  8 19:10 urandom
crw-rw-rw- 1 root mock  1,   5 Mar  8 19:10 zero
```

**Comment by rhatdan** [comment]
Does this work correctly with atomic-1.16.4?

**Comment by TomasTomecek** [comment]
No.

```
...
Upgraded:
  atomic.x86_64 1.16.4-1.fc27
...
$ atomic --debug pull --storage ostree docker:modularitycontainers/nginx
Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', image='docker:modularitycontainers/nginx', reg_type=None, storage=
'ostree')
g-io-error-quark: Not a regular file or symlink: loop1 (0)
Traceback (most recent call last):
  File "/usr/bin/atomic", line 189, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/pull.py", line 53, in pull_image
    be.pull_image(self.args.image, remote_image_obj, debug=self.args.debug, assumeyes=self.args.assumeyes)
  File "/usr/lib/python3.6/site-packages/Atomic/backends/_ostree.py", line 113, in pull_image
    return self.syscontainers.pull_image(image)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 166, in pull_image
    self._pull_image_to_ostree(self._get_ostree_repo(), image or self.args.image, True)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 157, in _pull_image_to_ostree
    image = self._pull_docker_image(repo, image.replace("docker:", "", 1))
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1172, in _pull_docker_image
    return self._pull_docker_tar(repo, temptar.name, image)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1193, in _pull_docker_tar
    self._pull_dockertar_layers(repo, imagebranch, temp_dir, input_layers, labels=labels)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1366, in _pull_dockertar_layers
    self._import_layers_into_ostree(repo, imagebranch, manifest, layers_to_import)
  File "/usr/lib/python3.6/site-packages/Atomic/syscontainers.py", line 1138, in _import_layers_into_ostree
    repo.write_directory_to_mtree(Gio.File.new_for_path(temp_dir), mtree, modifier)
GLib.GError: g-io-error-quark: Not a regular file or symlink: loop1 (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 211, in <module>
    sys.exit(1)
SystemExit: 1

$ atomic -v
1.16.4
```
