### ISSUE TITLE
KeyError during 'atomic scan' on F26AH

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#946]
Saw this running our tests against the early F26AH builds.

```
# atomic --debug scan --scanner openscap registry.access.redhat.com/rhel7
Created /run/atomic/2017-03-21-19-08-30-056267
docker run -t --rm -v /etc/localtime:/etc/localtime -v /run/atomic/2017-03-21-19-08-30-056267:/scanin -v /var/lib/atomic/openscap/2017-03-21-19-08-30-056267:/scanout:rw,Z -v /etc/oscapd:/etc/oscapd:ro registry.access.redhat.com/rhel7/openscap oscapd-evaluate scan --no-standard-compliance --targets chroots-in-dir:///scanin --output /scanout
Created /run/atomic/2017-03-21-19-08-30-056267/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d
Mounted 41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d to /run/atomic/2017-03-21-19-08-30-056267/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d
Creating the output dir at /var/lib/atomic/openscap/2017-03-21-19-08-30-056267
INFO:OpenSCAP Daemon one-off evaluator 0.1.6
WARNING:Can't import the 'docker' package. Container scanning functionality will be disabled.
INFO:Creating tasks directory at '/var/lib/oscapd/tasks' because it didn't exist.
INFO:Creating results directory at '/var/lib/oscapd/results' because it didn't exist.
INFO:Creating results work in progress directory at '/var/lib/oscapd/work_in_progress' because it didn't exist.
INFO:Evaluated EvaluationSpec, exit_code=0.
INFO:Evaluated EvaluationSpec, exit_code=0.
INFO:[100.00%] Scanned target 'chroot:///scanin/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d'
Unmounted /run/atomic/2017-03-21-19-08-30-056267/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d
'/scanin/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d'
Traceback (most recent call last):
  File "/usr/bin/atomic", line 189, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/scan.py", line 166, in scan
    self.output_results()
  File "/usr/lib/python3.6/site-packages/Atomic/scan.py", line 274, in output_results
    uuid = self.mount_paths[json_results['UUID'].rstrip('/')] if len(self.args.rootfs) == 0 \
KeyError: '/scanin/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 211, in <module>
    sys.exit(1)
SystemExit: 1

# rpm -q atomic docker
atomic-1.16.2-1.fc26.x86_64
docker-1.13.1-3.git5be1549.fc26.x86_64
```

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by miabbott** [comment]
Note, this is only happening on F26.  The `atomic 1.16.4` that is being tested in RHEL does not have this problem.

**Comment by rhatdan** [comment]
Excellent atomic 1.16.4 has been released to F26.

**Comment by miabbott** [comment]
> Note, this is only happening on F26. The atomic 1.16.4 that is being tested in RHEL does not have this problem.

Looks like I told a lie.  I can reproduce this on RHEL using `atomic 1.16.4` and `atomic 1.16.5`.  However, the system needs to have an overlay mount present in order to trigger this error.

I used `ostree admin unlock` to install an RPM and then re-ran the scan and had the same error returned to me on a RHELAH system.

I forget if we support using `atomic scan` with overlayfs present on a host?

**Comment by miabbott** [comment]
> Looks like I told a lie. I can reproduce this on RHEL using atomic 1.16.4 and atomic 1.16.5. However, the system needs to have an overlay mount present in order to trigger this error.

More lies!  I was encountering another error where `atomic scan` was failing to properly detected a supported image when overlayfs + SELinux were being used.

Sorry for the additional noise.

**Comment by miabbott** [comment]
The latest F26AH includes `atomic-1.16.5-1` which appears to fix things.  Or the new OpenSCAP container on the registry fixed it.
