### ISSUE TITLE
'atomic scan' + overlay mount + SELinux - is this supported?

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#951]
I've been running into issues where running `atomic scan` on an Atomic Host after using `ostree admin unlock` is incorrectly reporting that the RHEL7 image is `not supported for this scan.`

It appears that the overlay mount on `/usr` is causing the problem.  

My question is if this is a supported configuration?

See below for an example of the problem on F25 Atomic Host (using `atomic-1.15.1-1.fc25.x86_64`):

```
# findmnt | grep overlay

# atomic scan --scanner openscap registry.access.redhat.com/rhel7                                                                                                                           
docker run -t --rm -v /etc/localtime:/etc/localtime -v /run/atomic/2017-03-23-21-14-39-551415:/scanin -v /var/lib/atomic/openscap/2017-03-23-21-14-39-551415:/scanout:rw,Z -v /etc/oscapd:/etc/oscapd:ro registry.a
ccess.redhat.com/rhel7/openscap oscapd-evaluate scan --no-standard-compliance --targets chroots-in-dir:///scanin --output /scanout

registry.access.redhat.com/rhel7 (41a4953dbf957cf)

registry.access.redhat.com/rhel7 passed the scan

Files associated with this scan are in /var/lib/atomic/openscap/2017-03-23-21-14-39-551415.

# ostree admin unlock
Development mode enabled.  A writable overlayfs is now mounted on /usr.
All changes there will be discarded on reboot.

# atomic scan --scanner openscap registry.access.redhat.com/rhel7
docker run -t --rm -v /etc/localtime:/etc/localtime -v /run/atomic/2017-03-23-21-14-56-253200:/scanin -v /var/lib/atomic/openscap/2017-03-23-21-14-56-253200:/scanout:rw,Z -v /etc/oscapd:/etc/oscapd:ro registry.a
ccess.redhat.com/rhel7/openscap oscapd-evaluate scan --no-standard-compliance --targets chroots-in-dir:///scanin --output /scanout

registry.access.redhat.com/rhel7 (41a4953dbf957cf)

     registry.access.redhat.com/rhel7 is not supported for this scan.

Files associated with this scan are in /var/lib/atomic/openscap/2017-03-23-21-14-56-253200.

# atomic --debug scan --scanner openscap registry.access.redhat.com/rhel7                                                                                                                   
Created /run/atomic/2017-03-23-21-15-05-117845
docker run -t --rm -v /etc/localtime:/etc/localtime -v /run/atomic/2017-03-23-21-15-05-117845:/scanin -v /var/lib/atomic/openscap/2017-03-23-21-15-05-117845:/scanout:rw,Z -v /etc/oscapd:/etc/oscapd:ro registry.a
ccess.redhat.com/rhel7/openscap oscapd-evaluate scan --no-standard-compliance --targets chroots-in-dir:///scanin --output /scanout
Created /run/atomic/2017-03-23-21-15-05-117845/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d
Mounted {'ImageType': 'Docker', 'Created': 1487784636, 'input': 'registry.access.redhat.com/rhel7', 'VirtualSize': 192539213, 'ImageId': '41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d', 'Size'
: 192539213, 'Id': '41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d', 'Labels': {'authoritative-source-url': 'registry.access.redhat.com', 'Version': '7.3', 'vendor': 'Red Hat, Inc.', 'build-dat
e': '2017-02-22T12:22:18.266817', 'BZComponent': 'rhel-server-docker', 'description': 'The Red Hat Enterprise Linux Base image is designed to be a fully supported foundation for your containerized applications. 
 This base image provides your operations and application teams with the packages, language runtimes and tools necessary to run, maintain, and troubleshoot all of your applications. This image is maintained by R
ed Hat and updated regularly. It is designed and engineered to be the base layer for all of your containerized applications, middleware and utilites. When used as the source for all of your containers, only one 
copy will ever be downloaded and cached in your production environment. Use this image just like you would a regular Red Hat Enterprise Linux distribution. Tools like yum, gzip, and bash are provided by default.
 For further information on how this image was built look at the /root/anacanda-ks.cfg file.', 'release': '74', 'com.redhat.build-host': 'ip-10-29-120-147.ec2.internal', 'com.redhat.component': 'rhel-server-dock
er', 'Name': 'rhel7', 'io.openshift.tags': 'base rhel7', 'architecture': 'x86_64', 'version': '7.3', 'vcs-type': 'git', 'io.k8s.display-name': 'Red Hat Enterprise Linux 7', 'vcs-ref': '06e55ffd458c665f861599ac9c
7550a037d85ac7', 'summary': 'Provides the latest release of Red Hat Enterprise Linux 7 in a fully featured and supported base image.', 'name': 'rhel7', 'distribution-scope': 'public', 'Release': '74'}, 'ParentId
': '', 'RepoTags': ['registry.access.redhat.com/rhel7:latest'], 'RepoDigests': ['registry.access.redhat.com/rhel7@sha256:822cfa544c7c51d8bca1675dfd7ef5b5aaa205e222617f787868516eca2c6acc']} to /run/atomic/2017-03
-23-21-15-05-117845/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d
Creating the output dir at /var/lib/atomic/openscap/2017-03-23-21-15-05-117845
INFO:OpenSCAP Daemon one-off evaluator 0.1.6
WARNING:Can't import the 'docker' package. Container scanning functionality will be disabled.
INFO:Creating tasks directory at '/var/lib/oscapd/tasks' because it didn't exist.
INFO:Creating results directory at '/var/lib/oscapd/results' because it didn't exist.
INFO:Creating results work in progress directory at '/var/lib/oscapd/work_in_progress' because it didn't exist.
INFO:Evaluated EvaluationSpec, exit_code=0.
INFO:Evaluated EvaluationSpec, exit_code=0.
ERROR:Failed to scan target 'chroot:///scanin/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d' for vulnerabilities.
Traceback (most recent call last):
  File "/usr/bin/oscapd-evaluate", line 143, in scan_worker
    es.evaluate(config)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/evaluation_spec.py", line 473, in evaluate
    wip_result = self.evaluate_into_dir(config)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/evaluation_spec.py", line 470, in evaluate_into_dir
    return oscap_helpers.evaluate(self, config)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/oscap_helpers.py", line 300, in evaluate
    args = get_evaluation_args(spec, config)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/oscap_helpers.py", line 275, in get_evaluation_args
    ret.extend(spec.get_oscap_arguments(config))
  File "/usr/lib/python2.7/site-packages/openscap_daemon/evaluation_spec.py", line 444, in get_oscap_arguments
    ret.append(config.get_cve_feed(self.get_cpe_ids(config)))
  File "/usr/lib/python2.7/site-packages/openscap_daemon/config.py", line 402, in get_cve_feed
    return self.cve_feed_manager.get_cve_feed(cpe_ids)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/cve_feed_manager.py", line 219, in get_cve_feed
    "Can't find a supported CPE ID in %s" % (", ".join(cpe_ids))
RuntimeError: Can't find a supported CPE ID in 
INFO:[100.00%] Scanned target 'chroot:///scanin/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d'

registry.access.redhat.com/rhel7 (41a4953dbf957cf)

     registry.access.redhat.com/rhel7 is not supported for this scan.

Files associated with this scan are in /var/lib/atomic/openscap/2017-03-23-21-15-05-117845.

Unmounted /run/atomic/2017-03-23-21-15-05-117845/41a4953dbf957cfc562935239a3153a5da6101f32fa30da7b4a506f23cfcde9d

```

I found the following denials in the journal:

```
# journalctl -b --since "1 minute ago" | grep denied                                                                                                                                        Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/etc/passwd" dev="dm-4" ino=20977727 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=u
nconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/etc/ld.so.cache" dev="dm-4" ino=21020693 scontext=system_u:system_r:container_t:s0:c248,c605 tcont
ext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/etc/group" dev="dm-4" ino=21020748 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=un
confined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/etc/hosts" dev="dm-4" ino=21020701 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=un
confined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/usr/lib64/libnss_dns-2.17.so" dev="dm-4" ino=20975955 scontext=system_u:system_r:container_t:s0:c2
48,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/usr/lib64/libnss_dns-2.17.so" dev="dm-4" ino=20975955 scontext=system_u:system_r:container_t:s0:c2
48,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/usr/lib64/libnss_myhostname.so.2" dev="dm-4" ino=20975831 scontext=system_u:system_r:container_t:s
0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/usr/lib64/libnss_myhostname.so.2" dev="dm-4" ino=20975831 scontext=system_u:system_r:container_t:s
0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/usr/lib/rpm/rpmrc" dev="dm-4" ino=20976688 scontext=system_u:system_r:container_t:s0:c248,c605 tco
ntext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/usr/lib/rpm/macros" dev="dm-4" ino=20976679 scontext=system_u:system_r:container_t:s0:c248,c605 tc
ontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3899]: AVC avc:  denied  { open } for  pid=3899 comm="probe_rpminfo" path="/usr/lib/rpm/platform/x86_64-linux/macros" dev="dm-4" ino=18877645 scontext=system_u:system_r:conta
iner_t:s0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/etc/passwd" dev="dm-4" ino=20977727 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext
=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/etc/ld.so.cache" dev="dm-4" ino=21020693 scontext=system_u:system_r:container_t:s0:c248,c605 tco
ntext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/etc/group" dev="dm-4" ino=21020748 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=
unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/etc/hosts" dev="dm-4" ino=21020701 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=
unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/usr/lib64/libnss_dns-2.17.so" dev="dm-4" ino=20975955 scontext=system_u:system_r:container_t:s0:
c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/usr/lib64/libnss_dns-2.17.so" dev="dm-4" ino=20975955 scontext=system_u:system_r:container_t:s0:
c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/usr/lib64/libnss_myhostname.so.2" dev="dm-4" ino=20975831 scontext=system_u:system_r:container_t
:s0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/usr/lib64/libnss_myhostname.so.2" dev="dm-4" ino=20975831 scontext=system_u:system_r:container_t
:s0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/usr/lib/rpm/rpmrc" dev="dm-4" ino=20976688 scontext=system_u:system_r:container_t:s0:c248,c605 t
context=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/usr/lib/rpm/macros" dev="dm-4" ino=20976679 scontext=system_u:system_r:container_t:s0:c248,c605 
tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_rpmverify" path="/usr/lib/rpm/platform/x86_64-linux/macros" dev="dm-4" ino=18877645 scontext=system_u:system_r:con
tainer_t:s0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_worker" path="/var/lib/rpm/Packages" dev="dm-4" ino=27264009 scontext=system_u:system_r:container_t:s0:c248,c605 t
context=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3906]: AVC avc:  denied  { open } for  pid=3906 comm="probe_worker" path="/var/lib/rpm/Packages" dev="dm-4" ino=27264009 scontext=system_u:system_r:container_t:s0:c248,c605 t
context=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/etc/passwd" dev="dm-4" ino=20977727 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=u
nconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/etc/ld.so.cache" dev="dm-4" ino=21020693 scontext=system_u:system_r:container_t:s0:c248,c605 tcont
ext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/etc/group" dev="dm-4" ino=21020748 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=un
confined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/etc/hosts" dev="dm-4" ino=21020701 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=un
confined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/usr/lib64/libnss_dns-2.17.so" dev="dm-4" ino=20975955 scontext=system_u:system_r:container_t:s0:c2
48,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/usr/lib64/libnss_dns-2.17.so" dev="dm-4" ino=20975955 scontext=system_u:system_r:container_t:s0:c2
48,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/usr/lib64/libnss_myhostname.so.2" dev="dm-4" ino=20975831 scontext=system_u:system_r:container_t:s
0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/usr/lib64/libnss_myhostname.so.2" dev="dm-4" ino=20975831 scontext=system_u:system_r:container_t:s
0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/usr/lib/rpm/rpmrc" dev="dm-4" ino=20976688 scontext=system_u:system_r:container_t:s0:c248,c605 tco
ntext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/usr/lib/rpm/macros" dev="dm-4" ino=20976679 scontext=system_u:system_r:container_t:s0:c248,c605 tc
ontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3926]: AVC avc:  denied  { open } for  pid=3926 comm="probe_rpminfo" path="/usr/lib/rpm/platform/x86_64-linux/macros" dev="dm-4" ino=18877645 scontext=system_u:system_r:conta
iner_t:s0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/etc/passwd" dev="dm-4" ino=20977727 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext
=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/etc/ld.so.cache" dev="dm-4" ino=21020693 scontext=system_u:system_r:container_t:s0:c248,c605 tco
ntext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/etc/group" dev="dm-4" ino=21020748 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=
unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/etc/hosts" dev="dm-4" ino=21020701 scontext=system_u:system_r:container_t:s0:c248,c605 tcontext=
unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/usr/lib64/libnss_dns-2.17.so" dev="dm-4" ino=20975955 scontext=system_u:system_r:container_t:s0:
c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/usr/lib64/libnss_dns-2.17.so" dev="dm-4" ino=20975955 scontext=system_u:system_r:container_t:s0:
c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/usr/lib64/libnss_myhostname.so.2" dev="dm-4" ino=20975831 scontext=system_u:system_r:container_t
:s0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/usr/lib64/libnss_myhostname.so.2" dev="dm-4" ino=20975831 scontext=system_u:system_r:container_t
:s0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/usr/lib/rpm/rpmrc" dev="dm-4" ino=20976688 scontext=system_u:system_r:container_t:s0:c248,c605 t
context=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/usr/lib/rpm/macros" dev="dm-4" ino=20976679 scontext=system_u:system_r:container_t:s0:c248,c605 
tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_rpmverify" path="/usr/lib/rpm/platform/x86_64-linux/macros" dev="dm-4" ino=18877645 scontext=system_u:system_r:con
tainer_t:s0:c248,c605 tcontext=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_worker" path="/var/lib/rpm/Packages" dev="dm-4" ino=27264009 scontext=system_u:system_r:container_t:s0:c248,c605 t
context=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
Mar 23 21:16:25 fedora25ah-dev audit[3933]: AVC avc:  denied  { open } for  pid=3933 comm="probe_worker" path="/var/lib/rpm/Packages" dev="dm-4" ino=27264009 scontext=system_u:system_r:container_t:s0:c248,c605 t
context=unconfined_u:object_r:tmp_t:s0 tclass=file permissive=0
```

**Comment by miabbott** [comment]
Downstream BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1435702

**Comment by rhatdan** [comment]
As soon as you unlock on a rhel7 or Centos7 system, you are putting an overlay mount on the system, which breaks SELinux.  As of RHEL7.4 this should be fixed, until then it can not be supported with SELinux in enforcing mode.

**Comment by miabbott** [comment]
Could `atomic` do some sort of detection if the system was in an incompatible configuration and spit out an error message?  Otherwise, users will have no idea the reason for their failed scan.

Also, since I have also observed this on an F25 system, which version of the kernel contains support for overlay + SELinux?

**Comment by rhatdan** [comment]
Not sure on the version. This looks like the mounted container is mounted with a label of tmp_t?  IE All of the content inside of the container image is tmp_t.  @baude Where does atomic mount the content that is being scanned?  Is this with a devicemapper or overlay backend?

**Comment by miabbott** [comment]
> Is this with a devicemapper or overlay backend?

All my tests have been performed with a devicemapper backend.

**Comment by rhatdan** [comment]
@miabbott Can you give me access to this machine?  I have no idea what is going on?

**Comment by miabbott** [comment]
@rhatdan Sent an email with details

**Comment by miabbott** [comment]
The root cause was determined to be a mis-label of the overlay mount when using `ostree admin unlock`.  The label was `tmp_t` but should be `usr_t`.  Kudos to @rhatdan and @baude for getting to the bottom of this.

There is a patch for this at ostreedev/ostree#763

I'll close this once I get a chance to test the new version of ostree with this fix.

**Comment by miabbott** [comment]
The new ostree build landed in the latest [CentOS Continuous](https://wiki.centos.org/SpecialInterestGroup/Atomic/Devel) compose and I was able to successfully scan the RHEL7 image.

```
# atomic host status
State: idle
Deployments:
● centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
             Version: 7.2017.219 (2017-03-28 14:23:09)
              Commit: a3efb6666f3114fed7d5972b708d7f29e2dcfe94788cd31101b66343e39bb0e2
              OSName: centos-atomic-host
            Unlocked: development

# rpm -q ostree
ostree-2017.3.33-a88881039eef1e3db32f5cf0972099280cbe4227.d0e39fa72f9ba920eb1296c6dbe7ed95024c3de7.el7.centos.x86_64
# atomic scan --scanner openscap registry.access.redhat.com/rhel7                      
docker run -t --rm -v /etc/localtime:/etc/localtime -v /run/atomic/2017-03-28-14-51-15-275931:/scanin -v /var/lib/atomic/openscap/2017-03-28-14-51-15-275931:/scanout:rw,Z -v /etc/oscapd:/etc/oscapd:ro registry.access.redhat.com/rhel7/openscap oscapd-evaluate scan --no-standard-compliance --targets chroots-in-dir:///scanin --output /scanout

registry.access.redhat.com/rhel7 (41a4953dbf957cf)

registry.access.redhat.com/rhel7 passed the scan

Files associated with this scan are in /var/lib/atomic/openscap/2017-03-28-14-51-15-275931.

```
