### ISSUE TITLE
DBUS(atomic images list) raises attribute error

### ISSUE THREAD

**Issue by Edward5hen** [projectatomic/atomic#960]
1. When I use the dbus client to get the images list, below error raised:
```Traceback (most recent call last):
File "dbus_client.py", line 52, in <module>
    print dbus_client.images_list()
  File "dbus_client.py", line 19, in images_list
    return self.dbus_object.ImagesList(dbus_interface="org.atomic")
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 123, in reply_handler
    result = method(self, *p, **k)
  File "/usr/share/atomic/atomic_dbus.py", line 242, in ImagesList
    i = images.display_all_image_info()
  File "/usr/lib/python2.7/site-packages/Atomic/images.py", line 146, in display_all_image_info
    if self.args.filter:
AttributeError: Args instance has no attribute 'filter'
```

2. Then I commented below code(line146 and 147) in Atomic/images.py:
``` 
if self.args.filter:
    _images = [x for x in _images if self._filter_include_image(x)] 
```
and try again, but **0** is returned.
**Expected:** json format of images list should be returned.

3. If get the containers list via DBUS, similar attribute error is still raised.

**Comment by baude** [comment]
@Edward5hen are you using a specific version of atomic? With upstream master, this works perfectly for me. I tested with:

```
from atomic_dbus_client import AtomicDBus
adb = AtomicDBus()
print(adb.ImagesList())
```

and ran it as is (ofc with atomic_dbus.py running)

**Comment by baude** [comment]
https://github.com/projectatomic/atomic/pull/974 should fix the containerslist.

**Comment by baude** [comment]
Merged ... please re-open if not satisfied.
