### ISSUE TITLE
requires root privileges and touches /var during build

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#963]
https://ci.centos.org/view/Atomic/job/fahc-rdgo/1443/artifact/build-logs/failed/atomic/build.log

```
+ make PYTHON=/usr/bin/python3 PYLINT=true all
/usr/bin/python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import Atomic as _Atomic
  File "/builddir/build/BUILD/atomic-v1.16.3-52-f88187d5e42c496b4ed7a2ffc3a891847def925d/Atomic/__init__.py", line 1, in <module>
    from .pulp import PulpServer, PulpConfig
  File "/builddir/build/BUILD/atomic-v1.16.3-52-f88187d5e42c496b4ed7a2ffc3a891847def925d/Atomic/pulp.py", line 10, in <module>
    from . import util
  File "/builddir/build/BUILD/atomic-v1.16.3-52-f88187d5e42c496b4ed7a2ffc3a891847def925d/Atomic/util.py", line 37, in <module>
    os.makedirs(ATOMIC_VAR_LIB)
  File "/usr/lib64/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/atomic'
```

**Comment by jlebon** [comment]
@baude Basically, the `mkdir` shouldn't be triggered by importing the module. E.g. you can simply move it to create when needed.

**Comment by baude** [comment]
PTAL https://github.com/projectatomic/atomic/pull/966
